In [1]:
!nvidia-smi

Thu Apr 30 10:54:37 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   34C    P8              3W /   35W |    1273MiB /   4096MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1244    C+G   ...x64__8wekyb3d8bbwe\Photos.exe      N/A      |
|    0   N/A  N/A            3608    C+G   ...5n1h2txyewy\TextInputHost.exe      N/A      |
|    0   N/A  N/A            7372    C+G   ...App_cw5n1h2txyewy\LockApp.exe      N/A      |
|    0   N/A  N/A            8012    C+G   C:\Windows\explorer.exe               N/A      |
|    0   N/A  N/A            8668    C+G   ...2txyewy\CrossDeviceResume.exe      N/A      |
|    0   N/A  N/A            8960    C+G   ....0.3912.86\msedgewebview2.exe      N/A      |
|    0   N/A  N/A            9336    C+G   ...cw5n1h2txyewy\PrintDialog.exe      N/A      |
|    0   N/A  N/A           11444    C+G   ...t\Edge\Application\msedge.exe      N/A      |
|    0   N/A  N/A           11692    C+G   ...y\StartMenuExperienceHost.exe      N/A      |
|    0   N/A  N/A           11700    C+G   ..._cw5n1h2txyewy\SearchHost.exe      N/A      |
|    0   N/A  N/A           12356    C+G   ...em32\ApplicationFrameHost.exe      N/A      |
|    0   N/A  N/A           12668    C+G   ...xyewy\ShellExperienceHost.exe      N/A      |
|    0   N/A  N/A           13204    C+G   ...x64__8wekyb3d8bbwe\Photos.exe      N/A      |
|    0   N/A  N/A           14812    C+G   ....0.3912.60\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           17492    C+G   ...t\Edge\Application\msedge.exe      N/A      |
|    0   N/A  N/A           18948    C+G   ...4__8wekyb3d8bbwe\ms-teams.exe      N/A      |
|    0   N/A  N/A           19624    C+G   ...ng\AllShare\AllShareAgent.exe      N/A      |
|    0   N/A  N/A           19752    C+G   ...ms\Microsoft VS Code\Code.exe      N/A      |
|    0   N/A  N/A           20072    C+G   ...C\Acrobat\AcroCEF\AcroCEF.exe      N/A      |
|    0   N/A  N/A           20960    C+G   ....0.3912.86\msedgewebview2.exe      N/A      |
|    0   N/A  N/A           21980    C+G   ...icrosoft.AAD.BrokerPlugin.exe      N/A      |
|    0   N/A  N/A           23188    C+G   ...indows\System32\ShellHost.exe      N/A      |
|    0   N/A  N/A           24708    C+G   ...ntrolPanel\SystemSettings.exe      N/A      |
|    0   N/A  N/A           25252    C+G   ...crosoft OneDrive\OneDrive.exe      N/A      |
|    0   N/A  N/A           28884    C+G   ...4__8wekyb3d8bbwe\ms-teams.exe      N/A      |
|    0   N/A  N/A           30288    C+G   ...8wekyb3d8bbwe\M365Copilot.exe      N/A      |
+-----------------------------------------------------------------------------------------+

In [2]:
import os 
import requests
url= r"https://arxiv.org/pdf/2412.19437"
pdf_path=os.path.join(os.getcwd() , "Data_file.pdf")

if not os.path.exists(pdf_path):

    response= requests.get(url)
    if response.status_code == 200:
        with open(pdf_path,"wb") as f:
            f.write(response.content)
        print(f"[INFO] the file is downloaded at : {pdf_path}")
else:
    print(f"[INFO] file exist : {pdf_path} ")

[INFO] file exist : c:\Users\Tarek Hamada Hussien\Downloads\TEST\Self_traine_RAG_Model\Data_file.pdf

In [3]:
# import fitz  # PyMuPDF
# pages_and_texts=[]
# doc = fitz.open("Data_file.pdf")
# data_text = []

# for page_num , page in enumerate(doc):
#     text = page.get_text()
#     pages_and_texts.append({
#         "text_of_page" : text,
#         "page_number" : page_num + 1
#     })
# print(pages_and_texts[3]) 
# for text in pages_and_texts:
#     text["text_of_page"] =text["text_of_page"].replace(r"-\n"," ").strip()
# print(pages_and_texts[3] )

In [4]:
import fitz  # PyMuPDF

def clean_text(text: str):
    text = text.replace("\n", " ").strip()
    return text

def open_pdf(file_path:str):
    doc=fitz.open(file_path)
    pages_and_texts=[]
    for page_num , page in enumerate(doc):
        text = page.get_text()
        cleaned_text = clean_text(text)
        pages_and_texts.append({
            "text_of_page" : cleaned_text,
            "page_count_char" : len(cleaned_text),
            "page_count_word" : len(cleaned_text.split(" ")),
            "page_count_sentences" : len(cleaned_text.split(". ")),
            "tokens_num" : len(cleaned_text) // 4 , # i dont get it but it is what it is 
            "page_number" : page_num + 1
        })
    return pages_and_texts

pages_and_texts=open_pdf("Data_file.pdf")
pages_and_texts[3]

{'text_of_page': '1. Introduction In recent years, Large Language Models (LLMs) have been undergoing rapid iteration and evolution (Anthropic, 2024; Google, 2024; OpenAI, 2024a), progressively diminishing the gap to- wards Artificial General Intelligence (AGI). Beyond closed-source models, open-source models, including DeepSeek series (DeepSeek-AI, 2024a,b,c; Guo et al., 2024), LLaMA series (AI@Meta, 2024a,b; Touvron et al., 2023a,b), Qwen series (Qwen, 2023, 2024a,b), and Mistral series (Jiang et al., 2023; Mistral, 2024), are also making significant strides, endeavoring to close the gap with their closed-source counterparts. To further push the boundaries of open-source model capa- bilities, we scale up our models and introduce DeepSeek-V3, a large Mixture-of-Experts (MoE) model with 671B parameters, of which 37B are activated for each token. With a forward-looking perspective, we consistently strive for strong model performance and economical costs. Therefore, in terms of architecture, DeepSeek-V3 still adopts Multi-head Latent Attention (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for cost-effective training. These two architectures have been validated in DeepSeek- V2 (DeepSeek-AI, 2024c), demonstrating their capability to maintain robust model performance while achieving efficient training and inference. Beyond the basic architecture, we implement two additional strategies to further enhance the model capabilities. Firstly, DeepSeek-V3 pi- oneers an auxiliary-loss-free strategy (Wang et al., 2024a) for load balancing, with the aim of minimizing the adverse impact on model performance that arises from the effort to encourage load balancing. Secondly, DeepSeek-V3 employs a multi-token prediction training objective, which we have observed to enhance the overall performance on evaluation benchmarks. In order to achieve efficient training, we support the FP8 mixed precision training and implement comprehensive optimizations for the training framework. Low-precision training has emerged as a promising solution for efficient training (Dettmers et al., 2022; Kalamkar et al., 2019; Narang et al., 2017; Peng et al., 2023b), its evolution being closely tied to advancements in hardware capabilities (Luo et al., 2024; Micikevicius et al., 2022; Rouhani et al., 2023a). In this work, we introduce an FP8 mixed precision training framework and, for the first time, validate its effectiveness on an extremely large-scale model. Through the support for FP8 computation and storage, we achieve both accelerated training and reduced GPU memory usage. As for the training framework, we design the DualPipe algorithm for efficient pipeline parallelism, which has fewer pipeline bubbles and hides most of the communication during training through computation-communication overlap. This overlap ensures that, as the model further scales up, as long as we maintain a constant computation-to-communication ratio, we can still employ fine-grained experts across nodes while achieving a near-zero all-to-all communication overhead. In addition, we also develop efficient cross-node all-to-all communication kernels to fully utilize InfiniBand (IB) and NVLink bandwidths. Furthermore, we meticulously optimize the memory footprint, making it possible to train DeepSeek-V3 without using costly tensor parallelism. Combining these efforts, we achieve high training efficiency. During pre-training, we train DeepSeek-V3 on 14.8T high-quality and diverse tokens. The pre-training process is remarkably stable. Throughout the entire training process, we did not encounter any irrecoverable loss spikes or have to roll back. Next, we conduct a two-stage context length extension for DeepSeek-V3. In the first stage, the maximum context length is extended to 32K, and in the second stage, it is further extended to 128K. Following this, we conduct post-training, including Supervised Fine-Tuning (SFT) and Reinforcement Learning (RL) on the base model of DeepSeek-V3, to align it with human preferences and further unlock its potential. During the post-training stage, we distill the reasoning capability from the DeepSeek- R1 series of models, and meanwhile carefully maintain the balance between model accuracy 4',
 'page_count_char': 4248,
 'page_count_word': 594,
 'page_count_sentences': 26,
 'tokens_num': 1062,
 'page_number': 4}

In [5]:
import pandas as pd 

df = pd.DataFrame(pages_and_texts)
df.head(10)

,text_of_page,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
0,DeepSeek-V3 Technical Report DeepSeek-AI resea...,1817,238,11,454,1
1,Contents 1 Introduction 4 2 Architecture 6 2.1...,2634,919,766,658,2
2,4.5.3 Batch-Wise Load Balance VS. Sequence-Wis...,1715,572,462,428,3
3,"1. Introduction In recent years, Large Languag...",4248,594,26,1062,4
4,Training Costs Pre-Training Context Extension ...,3287,468,21,821,5
5,verification and reflection patterns of R1 int...,3475,457,23,868,6
6,… Router Input Hidden 𝐮𝐮𝑡𝑡 Output Hidden 𝐡𝐡𝑡𝑡 ...,1557,262,8,389,7
7,where c𝐾𝑉 𝑡 ∈R𝑑𝑐is the compressed latent vecto...,2236,353,9,559,8
8,where 𝑁𝑠and 𝑁𝑟denote the numbers of shared exp...,2901,455,17,725,9
9,Main Model (Next Token Prediction) Embedding L...,2904,451,23,726,10

In [6]:
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number
count,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00
std,799.86,178.18,124.63,199.99,15.44
min,699.00,99.00,1.00,174.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00
50%,2992.00,457.00,23.00,748.00,27.00
75%,3281.00,516.00,29.00,820.00,40.00
max,4248.00,919.00,766.00,1062.00,53.00

# Turn text to sentences

In [7]:
from spacy.lang.en import English

nlp= English()

# add sentencizer to pipeliine

nlp.add_pipe("sentencizer")

#example sentence to test
semtemces = "this my name . hellow mr.ahmed . what is your name ?"

doc = nlp(semtemces)
# list the sentences to show 
list(doc.sents)

[this my name ., hellow mr.ahmed ., what is your name ?]

# Now try the `data`

In [8]:
for page in pages_and_texts:
    page["sentences"] = list(nlp(page["text_of_page"]).sents)
    page["sentences_num"] =len(page["sentences"])

#make sure tha all sentences is string not spacy type
for page in pages_and_texts:
    page["sentences"]=[str(sentences) for sentences in page["sentences"]]

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25}

In [9]:
#read specific sentence
pages_and_texts[5]["sentences"][6]

'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.'

In [10]:
# see some statistics about this data 
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num
count,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94
std,799.86,178.18,124.63,199.99,15.44,14.44
min,699.00,99.00,1.00,174.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00

In [11]:
test=list(range(1,25))
input_list=[]
slice_size=10
x=[test[i:i+slice_size] for i in range(0,len(test),slice_size)]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24]]

In [12]:
def chunker (input_list : list[str],slice_size:int)->list[list[str]]:

    return[input_list[i:i+slice_size] for i in range(0,len(input_list),slice_size)]

for page in pages_and_texts:
    page["sentences_chunk"] = chunker(page["sentences"],slice_size)
    page["sentences_chunk_num"] =len( page["sentences_chunk"]) 

pages_and_texts[5]

{'text_of_page': 'verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance. Meanwhile, we also maintain control over the output style and length of DeepSeek-V3. Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA. Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA. While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. • Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models. Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain. For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks. In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2). Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design. Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4). Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5). Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6). 2. Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al., 2024) for economical training. Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks. For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c). 2.1. Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al., 2017) framework. For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2. Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6',
 'page_count_char': 3475,
 'page_count_word': 457,
 'page_count_sentences': 23,
 'tokens_num': 868,
 'page_number': 6,
 'sentences': ['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
  'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
  'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
  'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
  '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
  'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
  'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
  'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
  '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
  'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.',
  'In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
  'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
  'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
  'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
  'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
  '2.',
  'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
  '2024) for economical training.',
  'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
  'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).',
  '2.1.',
  'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
  '2017) framework.',
  'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
  'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6'],
 'sentences_num': 25,
 'sentences_chunk': [['verification and reflection patterns of R1 into DeepSeek-V3 and notably improves its reasoning performance.',
   'Meanwhile, we also maintain control over the output style and length of DeepSeek-V3.',
   'Summary of Core Evaluation Results • Knowledge: (1) On educational benchmarks such as MMLU, MMLU-Pro, and GPQA, DeepSeek-V3 outperforms all other open-source models, achieving 88.5 on MMLU, 75.9 on MMLU-Pro, and 59.1 on GPQA.',
   'Its performance is comparable to leading closed-source models like GPT-4o and Claude-Sonnet-3.5, narrowing the gap between open-source and closed-source models in this domain. (',
   '2) For factuality benchmarks, DeepSeek-V3 demonstrates superior performance among open-source models on both SimpleQA and Chinese SimpleQA.',
   'While it trails behind GPT-4o and Claude-Sonnet-3.5 in English factual knowledge (SimpleQA), it surpasses these models in Chinese factual knowledge (Chinese SimpleQA), highlighting its strength in Chinese factual knowledge. •',
   'Code, Math, and Reasoning: (1) DeepSeek-V3 achieves state-of-the-art performance on math-related benchmarks among all non-long-CoT open-source and closed-source models.',
   'Notably, it even outperforms o1-preview on specific benchmarks, such as MATH-500, demonstrating its robust mathematical reasoning capabilities. (',
   '2) On coding-related tasks, DeepSeek-V3 emerges as the top-performing model for coding competition benchmarks, such as LiveCodeBench, solidifying its position as the leading model in this domain.',
   'For engineering-related tasks, while DeepSeek-V3 performs slightly below Claude-Sonnet-3.5, it still outpaces all other models by a significant margin, demonstrating its competitiveness across diverse technical benchmarks.'],
  ['In the remainder of this paper, we first present a detailed exposition of our DeepSeek-V3 model architecture (Section 2).',
   'Subsequently, we introduce our infrastructures, encompassing our compute clusters, the training framework, the support for FP8 training, the inference deployment strategy, and our suggestions on future hardware design.',
   'Next, we describe our pre-training process, including the construction of training data, hyper-parameter settings, long- context extension techniques, the associated evaluations, as well as some discussions (Section 4).',
   'Thereafter, we discuss our efforts on post-training, which include Supervised Fine-Tuning (SFT), Reinforcement Learning (RL), the corresponding evaluations, and discussions (Section 5).',
   'Lastly, we conclude this work, discuss existing limitations of DeepSeek-V3, and propose potential directions for future research (Section 6).',
   '2.',
   'Architecture We first introduce the basic architecture of DeepSeek-V3, featured by Multi-head Latent Atten- tion (MLA) (DeepSeek-AI, 2024c) for efficient inference and DeepSeekMoE (Dai et al.,',
   '2024) for economical training.',
   'Then, we present a Multi-Token Prediction (MTP) training objective, which we have observed to enhance the overall performance on evaluation benchmarks.',
   'For other minor details not explicitly mentioned, DeepSeek-V3 adheres to the settings of DeepSeek- V2 (DeepSeek-AI, 2024c).'],
  ['2.1.',
   'Basic Architecture The basic architecture of DeepSeek-V3 is still within the Transformer (Vaswani et al.,',
   '2017) framework.',
   'For efficient inference and economical training, DeepSeek-V3 also adopts MLA and DeepSeekMoE, which have been thoroughly validated by DeepSeek-V2.',
   'Compared with DeepSeek-V2, an exception is that we additionally introduce an auxiliary-loss-free load balancing 6']],
 'sentences_chunk_num': 3}

In [13]:
df =pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_count_char,page_count_word,page_count_sentences,tokens_num,page_number,sentences_num,sentences_chunk_num
count,53.00,53.00,53.00,53.00,53.00,53.00,53.00
mean,2836.06,474.38,60.85,708.68,27.00,23.94,2.89
std,799.86,178.18,124.63,199.99,15.44,14.44,1.40
min,699.00,99.00,1.00,174.00,1.00,1.00,1.00
25%,2632.00,386.00,17.00,658.00,14.00,16.00,2.00
50%,2992.00,457.00,23.00,748.00,27.00,23.00,3.00
75%,3281.00,516.00,29.00,820.00,40.00,30.00,3.00
max,4248.00,919.00,766.00,1062.00,53.00,54.00,6.00

In [14]:
pages_and_chunk=[]
for page in pages_and_texts:
    for chunk in page["sentences_chunk"]:
        chunk_dict = {}

        # join all sentences in chunk to be one paragraphe
        paragragh = "".join(chunk).replace("  "," ").strip()
        chunk_dict ["paragraphe"] = paragragh
        
        # Calculate statistics
        words = paragragh.split(" ")
        word_count = len(words)
        char_count = len(paragragh)
        tokens_count = char_count // 4  # approximate tokens
        sentence_count = len(chunk)  # number of sentences in chunk
        
        # Store statistics
        chunk_dict["word_count"] = word_count
        chunk_dict["char_count"] = char_count
        chunk_dict["tokens_count"] = tokens_count
        chunk_dict["sentence_count"] = sentence_count
        chunk_dict ["page_number"] = page["page_number"]

        pages_and_chunk.append(chunk_dict)
pages_and_chunk[5] ,len(pages_and_chunk),len(pages_and_texts)

({'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
  'word_count': 298,
  'char_count': 830,
  'tokens_count': 207,
  'sentence_count': 10,
  'page_number': 3},
 153,
 53)

In [15]:
df = pd.DataFrame(pages_and_chunk)
df.describe().round(2)

       word_count  char_count  tokens_count  sentence_count  page_number
count      153.00      153.00        153.00          153.00       153.00
mean       157.03      974.48        243.26            8.29        26.52
std        145.88      584.64        146.14            2.95        13.86
min          1.00        1.00          0.00            1.00         1.00
25%         74.00      572.00        143.00            7.00        15.00
50%        134.00      912.00        228.00           10.00        28.00
75%        191.00     1301.00        325.00           10.00        39.00
max        877.00     2975.00        743.00           10.00        53.00

In [16]:
df[df["word_count"]<4]
pages_and_texts[8]

{'text_of_page': 'where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts. Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values. Auxiliary-Loss-Free Load Balancing. For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al., 2017) and diminish computational efficiency in scenarios with expert parallelism. Conventional solutions usually rely on the auxiliary loss (Fedus et al., 2021; Lepikhin et al., 2021) to avoid unbalanced load. However, too large an auxiliary loss will impair the model performance (Wang et al., 2024a). To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al., 2024a) to ensure load balance. To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (16) Note that the bias term is only used for routing. The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step. At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed. Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses. Complementary Sequence-Wise Auxiliary Loss. Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence. The sequence-wise balance loss encourages the expert load on each sequence to be balanced. 9',
 'page_count_char': 2901,
 'page_count_word': 455,
 'page_count_sentences': 17,
 'tokens_num': 725,
 'page_number': 9,
 'sentences': ['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
  'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
  'Auxiliary-Loss-Free Load Balancing.',
  'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
  '2017) and diminish computational efficiency in scenarios with expert parallelism.',
  'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
  '2021; Lepikhin et al.,',
  '2021) to avoid unbalanced load.',
  'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
  '2024a).',
  'To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
  '2024a) to ensure load balance.',
  'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
  '16) Note that the bias term is only used for routing.',
  'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
  'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
  'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
  'Complementary Sequence-Wise Auxiliary Loss.',
  'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
  'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.',
  '9'],
 'sentences_num': 21,
 'sentences_chunk': [['where 𝑁𝑠and 𝑁𝑟denote the numbers of shared experts and routed experts, respectively; FFN(𝑠) 𝑖 (·) and FFN(𝑟) 𝑖 (·) denote the 𝑖-th shared expert and the 𝑖-th routed expert, respectively; 𝐾𝑟denotes the number of activated routed experts; 𝑔𝑖,𝑡is the gating value for the 𝑖-th expert; 𝑠𝑖,𝑡is the token-to-expert affinity; e𝑖is the centroid vector of the 𝑖-th routed expert; and Topk(·, 𝐾) denotes the set comprising 𝐾highest scores among the affinity scores calculated for the 𝑡-th token and all routed experts.',
   'Slightly different from DeepSeek-V2, DeepSeek-V3 uses the sigmoid function to compute the affinity scores, and applies a normalization among all selected affinity scores to produce the gating values.',
   'Auxiliary-Loss-Free Load Balancing.',
   'For MoE models, an unbalanced expert load will lead to routing collapse (Shazeer et al.,',
   '2017) and diminish computational efficiency in scenarios with expert parallelism.',
   'Conventional solutions usually rely on the auxiliary loss (Fedus et al.,',
   '2021; Lepikhin et al.,',
   '2021) to avoid unbalanced load.',
   'However, too large an auxiliary loss will impair the model performance (Wang et al.,',
   '2024a).'],
  ['To achieve a better trade-off between load balance and model performance, we pioneer an auxiliary-loss-free load balancing strategy (Wang et al.,',
   '2024a) to ensure load balance.',
   'To be specific, we introduce a bias term 𝑏𝑖for each expert and add it to the corresponding affinity scores 𝑠𝑖,𝑡to determine the top-K routing: 𝑔′ 𝑖,𝑡= ( 𝑠𝑖,𝑡, 𝑠𝑖,𝑡+ 𝑏𝑖∈Topk({𝑠𝑗,𝑡+ 𝑏𝑗|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟), 0, otherwise. (',
   '16) Note that the bias term is only used for routing.',
   'The gating value, which will be multiplied with the FFN output, is still derived from the original affinity score 𝑠𝑖,𝑡. During training, we keep monitoring the expert load on the whole batch of each training step.',
   'At the end of each step, we will decrease the bias term by 𝛾if its corresponding expert is overloaded, and increase it by 𝛾if its corresponding expert is underloaded, where 𝛾is a hyper-parameter called bias update speed.',
   'Through the dynamic adjustment, DeepSeek-V3 keeps balanced expert load during training, and achieves better performance than models that encourage load balance through pure auxiliary losses.',
   'Complementary Sequence-Wise Auxiliary Loss.',
   'Although DeepSeek-V3 mainly relies on the auxiliary-loss-free strategy for load balance, to prevent extreme imbalance within any single sequence, we also employ a complementary sequence-wise balance loss: LBal = 𝛼 𝑁𝑟 ∑︁ 𝑖=1 𝑓𝑖𝑃𝑖, (17) 𝑓𝑖= 𝑁𝑟 𝐾𝑟𝑇 𝑇 ∑︁ 𝑡=1 1 \x00𝑠𝑖,𝑡∈Topk({𝑠𝑗,𝑡|1 ⩽𝑗⩽𝑁𝑟}, 𝐾𝑟)\x01 , (18) 𝑠′ 𝑖,𝑡= 𝑠𝑖,𝑡 Í𝑁𝑟 𝑗=1 𝑠𝑗,𝑡 , (19) 𝑃𝑖= 1 𝑇 𝑇 ∑︁ 𝑡=1 𝑠′ 𝑖,𝑡, (20) where the balance factor 𝛼is a hyper-parameter, which will be assigned an extremely small value for DeepSeek-V3; 1(·) denotes the indicator function; and 𝑇denotes the number of tokens in a sequence.',
   'The sequence-wise balance loss encourages the expert load on each sequence to be balanced.'],
  ['9']],
 'sentences_chunk_num': 3}

In [17]:
#filter out tokens less than 30
filtered_chunks = [chunk for chunk in pages_and_chunk if chunk["tokens_count"] >= 30]
filtered_chunks[111]

{'paragraphe': 'A study of bfloat16 for deep learning training.arXiv preprint arXiv:1905.12322, 2019.S. Krishna, K. Krishna, A. Mohananey, S. Schwarcz, A. Stambler, S. Upadhyay, and M. Faruqui.Fact, fetch, and reason: A unified evaluation of retrieval-augmented generation.CoRR, abs/2409.12941, 2024.doi: 10.48550/ARXIV.2409.12941.URL https://doi.org/10.485 50/arXiv.2409.12941.T. Kwiatkowski, J. Palomaki, O. Redfield, M. Collins, A. P. Parikh, C. Alberti, D. Epstein, I. Polosukhin, J. Devlin, K. Lee, K. Toutanova, L. Jones, M. Kelcey, M. Chang, A. M. Dai, J. Uszkoreit, Q. Le, and S. Petrov.Natural questions: a benchmark for question answering research.Trans.',
 'word_count': 84,
 'char_count': 648,
 'tokens_count': 162,
 'sentence_count': 10,
 'page_number': 39}

In [18]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

c:\Users\Tarek Hamada Hussien\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11310.43it/s]

In [19]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True

In [20]:
set = ["my name", "her name", "the naem"]
embeding = model.encode(set)
embeding = dict(zip(set,embeding))

embeding,embeding["my name"].shape

({'my name': array([-1.11268580e-01,  3.23448554e-02, -3.83406095e-02,  2.23898105e-02,
         -4.03140672e-02, -5.62008582e-02,  2.33329952e-01,  3.92086990e-02,
         -1.01079093e-02, -6.38170168e-02,  1.64090004e-02, -3.45564187e-02,
          4.02090475e-02, -7.56014735e-02, -8.34890269e-03,  2.65754685e-02,
         -1.42914746e-02,  6.17222628e-03, -8.46135467e-02, -7.72886276e-02,
         -4.17721942e-02,  6.27690554e-02, -3.23730674e-05, -2.02984791e-02,
         -8.92573446e-02,  6.10294519e-03, -3.12835686e-02,  9.11155790e-02,
         -3.69638763e-02, -1.61543325e-01, -3.80753976e-04,  7.48011237e-03,
          9.98783186e-02,  5.72648905e-02, -4.66821576e-03, -4.17357869e-02,
         -1.26731113e-01, -2.11647209e-02,  5.62064126e-02, -1.07810786e-02,
         -4.70564188e-03, -1.19292267e-01,  2.42646392e-02,  5.37947984e-03,
          7.11641647e-03,  7.88039062e-03,  6.28899375e-04,  2.45067067e-02,
          1.61230173e-02,  9.47958305e-02, -9.59324911e-02, -8.88254270e-02,
         -5.96604496e-02,  1.89628843e-02,  1.31215192e-02, -7.77191743e-02,
          2.44200807e-02,  5.09176999e-02, -3.09438957e-03,  2.27700104e-04,
          4.02659327e-02,  1.79442037e-02, -7.26719722e-02,  3.98123786e-02,
          1.57935694e-02,  8.13503191e-03, -6.94841985e-03,  1.39237260e-02,
          4.64229239e-03, -9.63738840e-03, -2.38478761e-02, -6.72974251e-03,
          7.07241818e-02, -3.35569754e-02, -1.96108017e-02, -1.45387501e-02,
          1.61476377e-02, -1.77206248e-02, -1.31568927e-02,  6.13829419e-02,
         -8.46485421e-02,  4.43953974e-03, -9.70008969e-02, -8.54696240e-03,
         -2.76288688e-02,  4.83488552e-02,  3.65964659e-02, -3.85117345e-02,
         -2.87032239e-02, -5.48662292e-03,  2.66992766e-03, -7.49976262e-02,
          2.27707271e-02, -3.73108499e-03, -2.44773272e-02, -5.23779169e-03,
         -3.77407356e-04, -4.05308232e-02, -3.87832448e-02,  1.85519427e-01,
         -6.50252551e-02,  3.38606313e-02, -5.62591776e-02,  7.47068971e-02,
         -7.21327262e-03, -8.54289532e-03, -5.87107874e-02,  5.19503327e-03,
          5.03454590e-03, -2.29809135e-02, -5.23379669e-02, -2.39632558e-02,
         -5.20041585e-02,  4.00795862e-02,  3.42810415e-02,  7.10861534e-02,
          2.96652270e-03, -2.60684248e-02,  3.05781867e-02, -2.95662098e-02,
          4.49147038e-02,  2.99034696e-02, -8.65571201e-02, -1.93888452e-02,
         -2.02057566e-02,  1.09100686e-02, -1.28697988e-03, -3.38961106e-33,
          5.94929978e-03,  1.89252961e-02, -4.11679241e-04,  1.40347689e-01,
          2.08697207e-02,  1.44509971e-02, -5.77048995e-02,  7.57384580e-03,
         -3.34116407e-02, -4.86456382e-04,  1.18632335e-02,  1.23980064e-02,
         -2.82271393e-02,  6.32571355e-02,  2.87447143e-02,  3.98513861e-02,
         -2.19962765e-02,  5.86499311e-02, -3.66561897e-02,  2.81827562e-02,
         -3.64034362e-02,  6.67515546e-02,  3.82383959e-03,  3.85377593e-02,
         -5.31675816e-02, -1.20789573e-01, -1.26687465e-02, -7.43082538e-02,
          3.59357297e-02,  2.43287627e-02, -5.68793975e-02, -1.62085015e-02,
          8.52153003e-02, -1.06991231e-02,  2.98596807e-02, -8.78666714e-02,
         -1.15062194e-02,  1.56422369e-02, -4.40782309e-02,  1.03963725e-01,
         -9.96416435e-03,  1.12467837e-02, -7.92487711e-02,  4.75009270e-02,
         -2.51976568e-02, -1.84205789e-02,  3.58203277e-02,  5.33687025e-02,
         -9.88210738e-02, -1.01148803e-02, -5.02877682e-02,  3.62837017e-02,
         -1.07462861e-01, -1.13403556e-04, -8.78018364e-02,  2.03307234e-02,
         -1.38523336e-03,  9.96502023e-03, -1.05820224e-01, -1.08255688e-02,
         -5.61658386e-03,  3.54209691e-02, -1.99717898e-02,  1.85143836e-02,
          1.84968058e-02, -4.77539450e-02,  7.75206834e-02, -5.72839044e-02,
          2.59806626e-02,  3.01388558e-02, -7.60096535e-02, -5.30696437e-02,
          4.44191787e-03,  4.09771055e-02,  7.15029538e-02,  6.62903115e-03,
         -8.63278098e-03,  5.87880351e-02, -3.33780348e-02, -9.79792327e-03,
          3.39137726e-02, -1.12670539e-02,  2.68001505e-03,  3.78638245e-02,
          2.98797525e-02, -2.79736565e-03, -1.43966833e-02, -3.69952768e-02,
         -1.53700756e-02, -3.44166346e-02, -1.34393811e-01, -1.39014679e-03,
          1.08393155e-01, -2.45960206e-02, -5.27150109e-02,  1.20526971e-33,
         -1.27881849e-02,  4.35465761e-02,  1.87255032e-02,  9.56210420e-02,
          4.67722490e-03, -2.69599799e-02,  5.32099605e-03,  1.07820198e-01,
          1.92448671e-03,  5.60386367e-02, -2.19700690e-02, -8.23150426e-02,
          4.67023486e-03, -2.90251663e-03,  8.16676021e-02,  4.96276692e-02,
          4.06118222e-02, -1.76346418e-03, -4.65383939e-02,  2.63397209e-03,
         -5.90299927e-02,  5.77562712e-02, -1.08629446e-02, -6.16721772e-02,
         -4.12750943e-03,  1.70052797e-02,  3.90952937e-02,  2.52950415e-02,
          7.08593577e-02,  6.80857226e-02,  5.44351758e-03,  2.39246991e-02,
         -1.16943397e-01,  2.93324869e-02, -2.60606948e-02,  6.45446628e-02,
         -1.89389065e-02, -1.98988859e-02,  1.02715604e-02, -3.32670496e-03,
         -1.41808679e-02,  3.20844166e-02, -7.18639269e-02,  1.08568087e-01,
         -1.31832883e-02, -3.98828387e-02, -5.78844808e-02,  3.01687978e-02,
          1.03621464e-02,  4.26096432e-02, -3.35613787e-02, -6.73616007e-02,
         -6.93707317e-02, -3.82362083e-02,  1.17583445e-03,  3.61948349e-02,
          6.44930303e-02,  2.16482673e-02,  9.53720789e-03,  4.65247547e-03,
          1.59357488e-02,  3.41445766e-02,  6.12317249e-02,  7.34104365e-02,
          3.04528587e-02, -1.78817566e-02, -6.13178425e-02, -4.10456955e-02,
         -2.72018500e-02, -4.76149954e-02, -5.27508892e-02,  2.03911848e-02,
         -4.46445271e-02,  2.69611403e-02, -9.46116671e-02,  3.20556872e-02,
          1.63121633e-02,  2.63475683e-02, -2.50775069e-02,  5.37288897e-02,
          3.02446969e-02,  8.66488665e-02, -2.48541292e-02,  3.00488584e-02,
          1.60619766e-02, -2.64488347e-02,  3.59426513e-02,  8.03071856e-02,
         -2.33003795e-02, -3.87402177e-02,  2.93709431e-02,  3.48941013e-02,
         -1.20452791e-02, -1.63013171e-02, -9.69538391e-02, -1.50699115e-08,
          4.22302820e-02,  5.01372255e-02,  3.11900005e-02, -4.23702644e-03,
          5.10957949e-02,  8.86452794e-02, -3.07836104e-03, -2.18302049e-02,
          4.13647629e-02,  6.56359866e-02,  9.79078040e-02,  5.34658059e-02,
          3.15143205e-02,  9.64244269e-03,  9.51067731e-02, -2.79178843e-02,
         -5.68721667e-02,  8.92900024e-03, -4.92045423e-03, -2.21010372e-02,
         -3.58192548e-02, -2.98429057e-02,  8.19764435e-02, -7.19111860e-02,
          4.26655933e-02,  9.13802627e-03,  3.62761356e-02,  9.37117264e-02,
         -5.74504025e-02,  7.81974196e-02,  1.13642039e-02,  1.17897809e-01,
          1.24910166e-02,  6.13725223e-02, -3.99509855e-02, -9.76376468e-04,
          2.87474915e-02,  8.35280567e-02,  5.63312918e-02, -8.02360382e-03,
         -3.31368595e-02,  5.76817393e-02,  9.86445546e-02, -1.26726497e-02,
         -6.93444610e-02,  6.50679171e-02, -2.79169413e-04, -1.52545450e-02,
         -4.63719992e-03, -2.10705642e-02,  8.71943962e-03,  1.70729607e-02,
          2.25879624e-02,  7.89606124e-02,  2.01135650e-02,  4.21369411e-02,
          3.23688239e-02,  5.68195693e-02, -6.11765124e-02, -5.45439497e-02,
          7.75277615e-02,  5.29304380e-03, -9.12822783e-02,  1.33656869e-02],
        dtype=float32),
  'her name': array([-1.08516812e-01,  1.40265273e-02, -1.97903439e-02,  4.03933004e-02,
         -3.66050489e-02, -1.11381628e-03,  1.42931893e-01,  4.01251987e-02,
         -9.60895885e-03, -7.14013427e-02,  2.60373130e-02, -9.37794000e-02,
         -1.03091663e-02, -7.65828341e-02, -4.02911492e-02,  7.74797201e-02,
          3.67319547e-02,  3.94580737e-02, -9.53144208e-02, -5.77405803e-02,
         -2.17363406e-02, -2.40650661e-02,  3.27846743e-02,  4.04388942e-02,
         -3.74304131e-02,  2.06179172e-03, -5.38016893e-02,  1.28083304e-02,
         -3.16409580e-02, -1.22112058e-01,  1.27528682e-02, -1.95463598e-02,
          4.58518155e-02,  7.62845501e-02, -1.12640094e-02,  3.25133465e-02,
         -7.22715184e-02,  4.53228094e-02,  2.71108281e-02, -1.35518443e-02,
         -1.94001030e-02, -1.14641204e-01, -4.72653061e-02, -4.64220382e-02,
         -3.94386649e-02, -4.94745523e-02,  5.11805527e-02,  3.23776193e-02,
          2.72550024e-02, -2.67372094e-02, -6.49755672e-02, -5.32744452e-02,
         -1.18825607e-01,  2.55614868e-03,  7.93129876e-02, -2.25096028e-02,
          5.34011386e-02,  5.47846928e-02,  3.82738300e-02,  1.02928197e-02,
          6.06006570e-02,  5.18807359e-02, -7.12646618e-02,  4.85623106e-02,
         -5.31428307e-03, -9.10788868e-03,  3.76583934e-02, -4.69222218e-02,
          3.90819572e-02,  6.33172365e-03,  2.00461615e-02,  3.55321281e-02,
         -1.72343792e-03, -3.88699099e-02,  2.61441935e-02,  1.99030954e-02,
          7.56488740e-02,  1.09233484e-02,  2.11198144e-02,  6.88376501e-02,
         -7.15844557e-02,  1.77171659e-02,  5.93788747e-04,  1.94032826e-02,
          4.28240793e-03,  4.30800878e-02, -3.16122361e-02, -2.20458470e-02,
         -2.73831841e-02, -5.10557108e-02, -4.97698188e-02, -6.01557046e-02,
          3.76523137e-02, -1.17023624e-02, -2.06190012e-02, -2.93967575e-02,
         -2.07708254e-02, -2.78658569e-02, -1.51966698e-02,  1.78603172e-01,
         -9.23539698e-02,  1.01476826e-01, -9.04797483e-03,  9.42860916e-02,
         -3.34173329e-02, -5.97187504e-02,  4.86570969e-02, -5.82067808e-03,
         -3.47071290e-02, -1.29232397e-02, -1.64540485e-03, -1.47645576e-02,
         -9.90035981e-02, -5.19064581e-03,  3.52939591e-02,  3.13790701e-02,
          4.73542027e-02, -1.23639675e-02,  2.38937978e-02, -9.74604562e-02,
          4.04632762e-02, -4.96868975e-02, -4.79107834e-02, -2.40672808e-02,
         -5.60440533e-02, -2.87502855e-02,  2.83523202e-02, -3.16461042e-33,
         -3.55150737e-02,  2.95765717e-02,  8.10843781e-02,  8.34557042e-02,
          5.95203601e-02,  2.11190376e-02,  1.59793049e-02,  1.16895102e-02,
          3.46239097e-03, -2.01443415e-02, -2.27793632e-03, -8.82628337e-02,
         -5.42954691e-02, -8.02553743e-02,  1.01886183e-01,  1.27110286e-02,
         -3.21838781e-02,  7.77680948e-02, -7.86051005e-02,  5.41978478e-02,
          4.28526029e-02,  8.47249776e-02,  2.49308236e-02,  5.01613729e-02,
         -3.17426324e-02, -9.03306678e-02,  7.80700073e-02,  1.17246043e-02,
          1.61149749e-03,  3.63856107e-02, -2.68512331e-02,  1.80520568e-04,
          8.83467570e-02, -1.63772907e-02,  5.22143021e-02, -4.44410853e-02,
         -5.81526849e-03, -1.12066604e-02,  3.63270962e-03,  7.74848089e-02,
          2.00558361e-02, -1.65880993e-02,  2.73299292e-02,  1.84894484e-02,
         -1.34903476e-01,  4.32648212e-02,  5.84352911e-02,  1.03550954e-02,
          4.11863960e-02, -6.93635884e-05, -9.41860825e-02,  3.53580154e-02,
         -1.00075282e-01,  5.65286316e-02, -6.15794919e-02,  8.11114460e-02,
          3.31929848e-02, -1.32226804e-02, -1.87827107e-02, -3.98739874e-02,
          1.16541451e-02,  2.19121352e-02, -6.86919019e-02,  9.83212050e-03,
          4.92209382e-02, -5.10650650e-02,  2.85478421e-02, -1.02851249e-01,
          3.24431807e-02,  1.23117333e-02, -1.13674067e-01,  1.87592655e-02,
          2.25785933e-02,  4.31681834e-02, -5.41480482e-02,  2.82280240e-02,
          3.29296701e-02, -2.86127534e-02, -3.13659310e-02, -5.98064950e-03,
          1.17117204e-02,  3.75699997e-02, -2.54160855e-02,  8.43513608e-02,
         -4.38703299e-02, -3.62573355e-03, -2.06886567e-02, -1.42937778e-02,
         -3.48394066e-02, -7.15545863e-02, -6.16803393e-02,  2.06668731e-02,
          7.54759163e-02, -4.97288778e-02, -2.12219935e-02,  1.31706189e-33,
         -5.28453290e-03,  1.54752620e-02, -4.34725024e-02,  6.07264563e-02,
          5.43512106e-02, -1.14345299e-02, -1.48576940e-03,  1.01141520e-01,
         -4.60984884e-03, -1.25182820e-02,  2.76288763e-02, -1.24480255e-01,
          1.22275706e-02, -1.49447555e-02,  6.50415048e-02,  6.65459409e-02,
          8.23930427e-02, -6.69729486e-02, -3.24602872e-02, -6.40190020e-02,
         -9.25135389e-02,  1.08706467e-02,  1.46333948e-02, -7.67764375e-02,
         -2.50701923e-02,  2.24010255e-02,  9.63629931e-02, -2.89402180e-03,
         -4.82729077e-02, -1.27476947e-02,  3.41591947e-02,  1.86355244e-02,
         -7.29230791e-02,  6.13724701e-02, -3.97584513e-02,  4.89615314e-02,
          2.06597745e-02, -4.81187999e-02,  2.89742295e-02,  2.80811824e-02,
          4.12800424e-02,  8.84455722e-03, -2.17010826e-02,  1.02579288e-01,
          2.75865085e-02,  2.12726314e-02, -1.27491001e-02,  4.89049889e-02,
          8.61027688e-02,  2.64374111e-02, -2.06164308e-02, -7.87166804e-02,
         -2.70624030e-02,  8.11807346e-03,  5.95772788e-02, -3.19411978e-02,
          5.81039600e-02,  1.95025578e-02,  3.71583849e-02,  5.88324107e-03,
          1.53963529e-02,  3.51784155e-02, -2.35251021e-02,  7.92885795e-02,
         -3.05617154e-02, -1.99385118e-02, -8.13734755e-02, -1.25664786e-01,
         -2.59873625e-02, -5.24826534e-02,  3.75152309e-03,  2.80721951e-02,
         -4.10410687e-02,  6.88031241e-02, -9.14725363e-02,  1.63114928e-02,
         -9.08274949e-02, -2.50381194e-02, -2.15020385e-02,  3.57075445e-02,
          1.56707801e-02,  2.72471290e-02, -5.09989001e-02,  1.73480134e-03,
          2.54246984e-02, -4.76679159e-03,  8.02696571e-02,  1.11472078e-01,
         -2.18368880e-02, -1.08616404e-01, -1.27692334e-02, -8.22653901e-03,
         -1.66712962e-02, -6.58633336e-02, -7.73727000e-02, -1.59770792e-08,
          1.07898703e-02, -4.41678148e-03,  5.39550707e-02, -6.93759546e-02,
          4.82009463e-02,  7.87589177e-02,  2.61550136e-02, -1.01903388e-02,
          2.86767874e-02,  7.04269558e-02,  8.22025314e-02,  2.00291499e-02,
          5.73524423e-02,  3.10402829e-02,  6.98653758e-02, -3.70384417e-02,
          1.93623435e-02,  1.15336157e-01, -4.57215169e-03,  1.14648081e-02,
         -6.67654164e-03, -4.16180864e-02,  5.23354746e-02, -1.36465162e-01,
          1.81709565e-02,  6.24540774e-03, -1.47890905e-02,  1.09797262e-01,
         -4.21142392e-02,  1.01671042e-02, -3.07445824e-02,  1.13257222e-01,
          3.45925279e-02,  1.96993519e-02,  1.25564833e-03,  3.80589925e-02,
          4.83894274e-02,  2.26374753e-02, -1.67597719e-02,  3.04050911e-02,
         -1.51804360e-02,  2.86381487e-02,  9.29250941e-02, -2.69179866e-02,
         -5.29071726e-02,  2.60877572e-02,  1.27067761e-02, -4.53397073e-02,
         -2.70356843e-03, -1.21021373e-02, -7.78902089e-03,  1.35551188e-02,
          4.36936915e-02,  3.78443599e-02, -2.25434527e-02, -1.41144097e-02,
          2.71068811e-02, -2.39804164e-02, -3.96824628e-02,  1.36298346e-04,
          7.66982278e-03,  1.05080632e-02,  6.80240244e-02,  1.96243692e-02],
        dtype=float32),
  'the naem': array([-6.02948219e-02,  1.08011059e-01, -4.00736816e-02,  2.84986367e-04,
         -5.78279607e-02,  3.90510485e-02,  1.63081363e-02, -6.27290308e-02,
         -2.72917673e-02,  6.48954362e-02, -1.36010274e-02, -1.12080656e-01,
          4.29547578e-02, -3.33018899e-02,  3.84274013e-02,  1.98137830e-04,
         -9.92214493e-03,  3.54607916e-03, -1.39897941e-02, -5.76529317e-02,
         -3.93402874e-02,  4.99700382e-02,  2.77685113e-02, -9.71351005e-03,
         -7.29377121e-02,  3.06804606e-04,  5.28396107e-02,  1.97455939e-02,
          6.62655681e-02, -1.39705896e-01,  5.01708651e-04,  6.13604449e-02,
         -2.77932324e-02,  1.24620097e-02, -6.92578256e-02, -7.66454358e-03,
         -6.53420836e-02, -5.53792249e-03,  1.61085241e-02,  6.49706181e-03,
          7.51554444e-02, -4.55971584e-02, -3.45253339e-03, -3.36859487e-02,
          3.02659851e-02, -7.05948845e-02, -2.51310803e-02, -1.06170215e-02,
          4.80370149e-02,  5.61028048e-02,  3.07876430e-02, -5.77379987e-02,
         -2.93143447e-02,  2.36564688e-02,  6.86284378e-02,  3.42092142e-02,
         -3.66425663e-02, -1.07707500e-01,  2.47657467e-02, -1.87080668e-03,
          8.02794397e-02, -6.56677922e-03, -7.98377991e-02,  6.52273372e-02,
          6.82052225e-02, -9.37174559e-02,  6.07989468e-02,  3.30209956e-02,
         -3.37643698e-02,  2.64172070e-02,  3.17097381e-02, -5.40623777e-02,
          7.14883283e-02, -5.85954294e-05, -5.46505712e-02, -2.46139779e-03,
          6.93024918e-02,  2.13216897e-02,  4.47886586e-02, -1.18316412e-02,
          3.43478993e-02,  3.82323898e-02,  3.36475521e-02, -3.92940678e-02,
          5.31843156e-02, -2.18143081e-03,  8.81356597e-02, -2.54524779e-03,
          2.20382493e-02,  3.63924690e-02, -5.86665832e-02, -3.01842093e-02,
         -8.23798776e-03, -4.73331064e-02,  3.13263424e-02, -3.42283919e-02,
         -2.73819845e-02,  1.87601298e-02,  1.42660839e-02,  1.50501087e-01,
          8.95082578e-02,  1.07485510e-01,  3.75266606e-03,  2.73721516e-02,
          2.50877403e-02,  1.64601430e-02,  1.33112613e-02,  9.83587839e-03,
         -1.44914966e-02,  7.16948360e-02, -4.74362671e-02, -1.86514463e-02,
         -2.84116566e-02, -5.88079123e-03,  3.09783909e-02, -2.49706171e-02,
         -1.90918818e-02, -2.12573130e-02,  5.94183151e-03,  2.15574261e-02,
          6.16728701e-03, -8.75436589e-02, -8.20264444e-02,  3.19139473e-02,
          3.29091512e-02,  5.75121269e-02, -1.16018280e-02, -3.45253013e-33,
         -1.07773654e-02,  7.30660232e-03, -1.63617432e-02, -4.64672670e-02,
          3.70621644e-02,  2.73215417e-02, -2.31236648e-02,  5.66564389e-02,
         -9.57396403e-02, -1.78244058e-02, -2.85459626e-02,  7.88215175e-02,
         -7.85891190e-02,  1.38537372e-02,  8.36979970e-02,  1.03458129e-02,
         -7.59367272e-02, -2.64888816e-02, -3.77846211e-02, -9.53301936e-02,
         -1.12825729e-01,  1.13505073e-01,  7.91859720e-03,  4.91239764e-02,
         -4.25062217e-02,  2.93205529e-02, -2.66452413e-02, -8.48129913e-02,
         -2.70097610e-02,  3.14407647e-02,  4.99393456e-02,  4.24260758e-02,
         -5.03373146e-02,  4.26193215e-02, -8.63207206e-02, -7.60602532e-03,
         -2.76761297e-02, -2.03614552e-02, -5.48336618e-02, -3.26869301e-02,
         -3.44958715e-02,  2.51876265e-02,  1.70821827e-02,  6.42866790e-02,
         -8.01583827e-02, -4.63353433e-02, -1.50233628e-02, -6.26033098e-02,
          8.19116607e-02,  2.78966278e-02,  2.92818109e-03, -3.42847942e-03,
         -4.39037941e-02, -2.01128069e-02,  9.56659298e-03, -1.93481166e-02,
          1.94190754e-04,  4.55720723e-02,  6.61208257e-02, -1.77856572e-02,
          3.08940839e-02,  4.35537733e-02,  3.67996395e-02,  9.71465111e-02,
          3.79517078e-02,  3.49885821e-02, -6.32042810e-03, -6.03008382e-02,
          5.28266318e-02, -3.05552408e-02, -4.74490337e-02,  5.96354604e-02,
          6.59352094e-02,  7.80555382e-02, -1.09362078e-03,  1.21456785e-02,
         -5.06829657e-03, -8.68264958e-02, -9.48877186e-02, -3.95371802e-02,
          2.56637372e-02,  5.39868325e-02, -2.76523270e-02,  6.43403754e-02,
          3.58118862e-02, -1.93711761e-02, -2.32705493e-02, -1.75263323e-02,
          1.40554206e-02, -2.48366240e-02,  1.45109519e-02,  4.32571545e-02,
          1.46898357e-02, -6.47579655e-02, -5.66580407e-02,  3.23796090e-33,
          2.35630684e-02,  1.24059683e-02, -1.02182612e-01,  6.69505745e-02,
          6.45909831e-02, -4.55888771e-02,  4.77873981e-02,  2.63668410e-02,
         -1.10716738e-01,  3.60688642e-02,  1.58360135e-02, -2.84001026e-02,
          1.29867494e-01,  4.72247489e-02,  8.71693641e-02, -5.97081110e-02,
          1.27869129e-01, -8.50948021e-02,  2.15540100e-02, -3.34259197e-02,
          2.41573993e-02, -3.29210311e-02,  1.49753662e-02, -1.72330830e-02,
          1.08727915e-02,  7.22939298e-02,  1.39474561e-02, -7.08193928e-02,
         -7.42303208e-02, -2.18185019e-02,  1.94083285e-02,  3.13056670e-02,
         -1.57291330e-02,  9.62476805e-03, -4.63565588e-02,  3.84134501e-02,
          2.73784064e-02,  6.42660186e-02, -6.87038451e-02, -4.55769412e-02,

In [21]:
print(type(pages_and_chunk[0]))
print(pages_and_chunk[0])

<class 'dict'>
{'paragraphe': 'DeepSeek-V3 Technical Report DeepSeek-AI research@deepseek.com Abstract We present DeepSeek-V3, a strong Mixture-of-Experts (MoE) language model with 671B total parameters with 37B activated for each token.To achieve efficient inference and cost-effective training, DeepSeek-V3 adopts Multi-head Latent Attention (MLA) and DeepSeekMoE architec- tures, which were thoroughly validated in DeepSeek-V2.Furthermore, DeepSeek-V3 pioneers an auxiliary-loss-free strategy for load balancing and sets a multi-token prediction training objective for stronger performance.We pre-train DeepSeek-V3 on 14.8 trillion diverse and high-quality tokens, followed by Supervised Fine-Tuning and Reinforcement Learning stages to fully harness its capabilities.Comprehensive evaluations reveal that DeepSeek-V3 outperforms other open-source models and achieves performance comparable to leading closed-source models.Despite its excellent performance, DeepSeek-V3 requires only 2.788M H800 GPU hours for its full training.In addition, its training process is remarkably stable.Throughout the entire training process, we did not experience any irrecoverable loss spikes or perform any rollbacks.The model checkpoints are available at https://github.com/deepseek-ai/DeepSeek-V3.MMLU-Pro (EM) GPQA-Diamond (Pass@1) MATH 500 (EM) AIME 2024 (Pass@1) Codeforces (Percentile) SWE-bench Verified (Resolved) 0 20 40 60 80 100 Accuracy / Percentile (%) 75.9 59.1 90.2 39.2 51.6 42.0 66.2 41.3 74.7 16.7 35.6 22.6 71.6 49.0 80.0 23.3 24.8 23.8 73.3 51.1 73.8 23.3 25.3 24.5 72.6 49.9 74.6 9.3 23.6 38.8 78.0 65.0 78.3 16.0 20.3 50.8 DeepSeek-V3 DeepSeek-V2.5 Qwen2.5-72B-Inst Llama-3.1-405B-Inst GPT-4o-0513 Claude-3.5-Sonnet-1022 Figure 1 | Benchmark performance of DeepSeek-V3 and its counterparts.', 'word_count': 222, 'char_count': 1767, 'tokens_count': 441, 'sentence_count': 10, 'page_number': 1}

In [22]:
from tqdm import tqdm

for chunk in tqdm(pages_and_chunk):
    chunk["embedding"] = model.encode(chunk["paragraphe"], device="cuda")

100%|██████████| 153/153 [00:00<00:00, 170.99it/s]

In [23]:
import random
random.sample(pages_and_chunk,k=1)

[{'paragraphe': 'selects only 8 routed experts in practice, it can scale up this number to a maximum of 13 experts (4 nodes × 3.2 experts/node) while preserving the same communication cost.Overall, under such a communication strategy, only 20 SMs are sufficient to fully utilize the bandwidths of IB and NVLink.In detail, we employ the warp specialization technique (Bauer et al.,2014) and partition 20 SMs into 10 communication channels.During the dispatching process, (1) IB sending, (2) IB-to-NVLink forwarding, and (3) NVLink receiving are handled by respective warps.The number of warps allocated to each communication task is dynamically adjusted according to the actual workload across all SMs.Similarly, during the combining process, (1) NVLink sending, (2) NVLink-to-IB forwarding and accumulation, and (3) IB receiving and accumulation are also handled by dynamically adjusted warps.In addition, both dispatching and combining kernels overlap with the computation stream, so we also consider their impact on other SM computation kernels.Specifically, we employ customized PTX (Parallel Thread Execution) instructions and auto-tune the communication chunk size, which significantly reduces the use of the L2 cache and the interference to other SMs.3.2.3.',
  'word_count': 180,
  'char_count': 1246,
  'tokens_count': 311,
  'sentence_count': 10,
  'page_number': 14,
  'embedding': array([-2.54815482e-02, -4.76328321e-02,  5.65874055e-02,  9.74718016e-03,
         -1.55159319e-02, -8.10138434e-02,  6.42007581e-05,  4.23459746e-02,
         -8.91469233e-03, -2.90637296e-02, -5.11103496e-02,  1.43073974e-02,
          1.93220209e-02, -3.30106542e-02,  1.22526698e-02, -4.24180403e-02,
          1.17331564e-01, -1.62144862e-02, -1.32309437e-01, -4.26265597e-02,
          4.04202379e-02, -1.72593519e-02,  1.67055894e-02, -2.72176787e-02,
          6.24911487e-02, -3.46083380e-02, -1.69527996e-02, -6.24091811e-02,
          2.86052097e-02, -3.90870236e-02, -1.23073382e-03,  6.43795952e-02,
         -3.69030759e-02,  3.73410098e-02, -1.25970185e-01,  3.22717279e-02,
         -5.04865050e-02,  4.37300056e-02, -3.52757238e-02, -4.78870943e-02,
         -5.77440411e-02,  7.71153427e-05, -1.18047139e-02,  5.66604212e-02,
          5.42249605e-02, -5.19272266e-03,  4.60252091e-02,  3.89785804e-02,
         -1.37985731e-02, -5.46976030e-02, -4.41140048e-02, -2.13489775e-02,
          5.57017513e-02,  9.51699466e-02,  5.23870753e-04,  6.44305795e-02,
         -4.48599719e-02,  4.15798463e-02,  7.79178441e-02,  9.13913772e-02,
         -2.27257721e-02, -4.39417027e-02, -5.37641346e-02, -6.27108589e-02,
         -1.09955780e-02, -5.90453930e-02,  6.50276393e-02,  3.27449702e-02,
         -1.27091573e-03,  2.26013884e-02, -3.02279741e-03, -5.24245435e-03,
         -2.67776139e-02,  8.35708380e-02, -6.39015576e-03,  5.49166836e-02,
          4.87257876e-02, -6.29415317e-03, -3.49153504e-02, -5.52464016e-02,
          4.31986637e-02,  1.14049070e-01,  1.45333689e-02, -7.47851655e-02,
          5.79558574e-02, -2.86494046e-02, -3.10188364e-02,  6.34367988e-02,
          4.00519744e-02,  2.01326106e-02,  2.48612948e-02,  1.42739918e-02,
          1.09439222e-02,  3.77650261e-02,  1.16742933e-02,  2.97350958e-02,
         -7.67555609e-02, -2.63407491e-02,  1.52116613e-02,  7.52784684e-02,
          3.00987344e-02,  1.90122388e-02, -1.29137086e-02,  5.92511743e-02,
         -2.18762029e-02, -1.49330019e-03,  7.39084557e-02,  7.72056058e-02,
          1.55664859e-02, -2.10715905e-02,  3.25059071e-02,  5.50274402e-02,
         -1.87324639e-02, -2.52063405e-02, -7.02400729e-02,  7.57389702e-03,
          7.87626766e-03,  5.71840368e-02,  4.79307510e-02,  6.88051730e-02,
         -1.00323483e-01, -6.57339171e-02, -4.94720275e-03,  8.94334260e-03,
          1.17456412e-03,  5.60545456e-03, -8.00062716e-02,  2.35247368e-33,
         -1.02810383e-01,  7.69263580e-02, -3.41685377e-02, -9.27233603e-03,
          4.60707024e-03, -6.13165833e-02,  3.40817571e-02, -1.53963277e-02,
          8.22421256e-03, -7.55187571e-02, -5.72115928e-02, -1.89148560e-02,
          2.35033240e-02,  2.65133823e-03,  6.98348358e-02, -5.00248000e-02,
         -1.74800809e-02,  6.69867843e-02,  3.85699645e-02, -4.49996255e-03,
          4.75567318e-02,  7.04852911e-03, -3.58464383e-02, -3.08834463e-02,
          2.98488028e-02, -1.79119669e-02,  6.14950173e-02, -1.17176302e-01,
          3.37636769e-02,  2.48915404e-02, -5.56115843e-02, -8.49333778e-03,
          3.68733965e-02,  3.29302363e-02,  3.67712751e-02, -1.24351699e-02,
         -2.35011298e-02, -7.56222755e-02,  1.33477766e-02, -1.09738419e-02,
         -4.55942526e-02,  2.29868684e-02, -3.12810503e-02, -1.40139554e-02,
         -1.43087804e-01, -6.61028251e-02, -4.88111712e-02,  3.75046320e-02,
         -8.26688781e-02, -3.22589166e-02,  7.13006780e-02,  2.65252292e-02,
          5.41924424e-02, -4.84360848e-04,  1.08663388e-01, -2.36295145e-02,
          2.33316217e-02,  2.23360453e-02,  9.97976139e-02,  1.53997794e-01,
         -3.41484435e-02, -9.31779370e-02, -7.68940598e-02,  7.30712935e-02,
          6.88374937e-02, -9.70266759e-03, -5.28282374e-02,  1.58139654e-02,
          2.07786448e-03,  3.72646302e-02, -9.22648311e-02,  6.56909496e-02,
          5.01175299e-02,  4.57955059e-03, -4.08907747e-03,  3.42275128e-02,
         -4.03716508e-03, -1.37239350e-02,  2.35885452e-03,  1.61391739e-02,
         -1.17219336e-01,  9.22663286e-02, -9.80306417e-04, -2.29267944e-02,
          6.11656196e-02, -5.88137917e-02, -4.71485928e-02, -5.71776293e-02,
         -1.44149046e-02,  5.35969958e-02, -5.47137037e-02, -4.08081198e-03,
          3.98016870e-02,  1.80582311e-02, -6.67916387e-02, -1.42488237e-33,
         -4.33347039e-02,  7.34745041e-02, -6.81097060e-02,  7.11765960e-02,
         -5.06269112e-02, -3.09757143e-02, -8.15421809e-03, -3.08875199e-02,
         -9.65546668e-02, -6.10193536e-02, -1.01872139e-01, -7.91158993e-03,
          6.31954372e-02, -4.00758721e-03,  1.96372569e-02, -3.85422371e-02,
          3.82771790e-02,  5.09930588e-02, -4.97314334e-03,  2.94561516e-02,
          1.05536785e-02,  2.69812904e-02, -4.68783937e-02,  1.21403113e-02,
          2.92184595e-02,  1.78516824e-02, -1.06468415e-02,  1.19787961e-01,
         -4.09145793e-03, -2.62846518e-03,  3.39154974e-02, -5.02652377e-02,
          4.09174757e-03, -4.12898883e-02,  7.06928447e-02,  4.67046201e-02,
          2.47588381e-03,  5.73061779e-02,  1.13537163e-01,  9.09303799e-02,
          1.28795609e-01, -1.89085223e-03, -7.39385858e-02,  2.91700219e-03,
         -2.54021436e-02, -4.77729589e-02, -1.11871123e-01,  5.96976315e-04,
         -4.61655669e-02, -6.57774210e-02,  6.73808157e-02, -3.65606323e-02,
          5.73272631e-03,  3.64209563e-02,  1.20990886e-03, -2.24689171e-02,
          5.93665354e-02,  6.87474199e-03,  5.64701371e-02,  4.58936905e-03,
          4.59956266e-02, -7.89938644e-02,  1.02586292e-01, -1.13951880e-02,
          5.58741242e-02,  3.56463343e-02,  1.96663905e-02, -7.18379170e-02,
         -2.77363006e-02,  7.85433650e-02, -2.54007895e-02, -4.82314304e-02,
         -4.52685207e-02,  5.57900220e-03,  3.21807452e-02,  1.28036728e-02,
          3.54729742e-02,  4.47975099e-03, -6.17081262e-02,  4.97668758e-02,
         -4.51389477e-02,  8.42023045e-02,  2.02521514e-02, -2.27110945e-02,
         -4.78910049e-03,  1.03620671e-01,  8.28086436e-02,  3.38106416e-02,
          4.13578600e-02, -5.25308307e-03,  6.70639100e-04, -8.15751031e-02,
          1.14983628e-02,  3.02193966e-02, -6.53861463e-02, -5.08181834e-08,
          1.23514561e-03, -4.59952578e-02,  2.82911409e-04,  1.56587809e-02,
          2.92268600e-02, -1.45320287e-02, -5.98883927e-02,  4.12162190e-04,
          5.38742654e-02,  1.70746166e-02,  6.73163533e-02, -1.09244317e-01,
         -2.41971724e-02, -6.29698252e-03,  9.89628434e-02,  8.79707281e-03,
         -1.79121625e-02, -8.09719786e-02, -8.11412483e-02, -1.06459754e-02,
         -5.85272256e-03,  3.05425450e-02,  1.98964179e-02,  8.76404271e-02,
         -1.50612015e-02, -4.35115956e-02,  4.65719625e-02,  3.37400436e-02,
          2.01074239e-02, -8.45357403e-02, -5.48199005e-02,  7.99025223e-03,
         -1.93268042e-02, -2.47755833e-03, -6.58546612e-02,  3.48301940e-02,
          2.00244319e-02, -7.02855438e-02,  3.94608602e-02,  1.03977844e-01,
          5.28497845e-02,  4.38933866e-03,  3.27667072e-02,  3.65201533e-02,
          8.38969499e-02, -1.46717299e-02, -9.87378135e-02, -7.44951016e-04,
         -5.71003482e-02, -3.65645252e-03,  9.12115257e-03,  6.90296665e-02,
         -7.67283589e-02,  6.20436966e-02,  2.73517873e-02, -5.29267341e-02,
          3.11201178e-02, -9.18834656e-02,  5.40726520e-02,  4.04602587e-02,
          1.95374377e-02, -3.07924040e-02, -4.39189374e-02, -5.17551340e-02],
        dtype=float32)}]

In [24]:
page_and_Embedding_df = pd.DataFrame(pages_and_chunk)
page_and_Embedding_file_name="page_and_Embedding.csv"
page_and_Embedding_path = os.path.join(os.getcwd(),page_and_Embedding_file_name)
page_and_Embedding_df.to_csv(page_and_Embedding_path,index=False)

In [25]:
pages_and_chunk[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': array([-5.76342642e-02,  1.86270513e-02, -6.96300939e-02, -5.02151484e-03,
        -6.43548295e-02,  5.39917722e-02, -4.61325161e-02,  3.96140479e-02,
        -5.72230071e-02,  5.44097507e-03, -4.39483449e-02, -6.78690989e-03,
         4.00274098e-02, -1.59040969e-02,  7.62041006e-03,  4.98709492e-02,
         1.28310844e-01, -3.56771424e-02, -4.98869866e-02, -8.15588683e-02,
         4.34629619e-02, -4.59041297e-02,  8.90599862e-02,  1.54037271e-02,
        -7.79619813e-02,  3.06390580e-02, -5.25192842e-02, -6.64412901e-02,
         3.31790484e-02, -6.93642348e-02, -6.77236822e-03,  3.17600835e-03,
         5.10904342e-02, -8.24809149e-02, -8.37938786e-02,  1.99514590e-02,
        -5.22203557e-02, -5.73823750e-02,  1.78819466e-02,  2.67784391e-02,
         1.22638667e-04, -3.79560366e-02,  2.66230456e-03,  2.12215632e-02,
         3.83331478e-02, -2.20189728e-02, -5.95768988e-02, -2.69228090e-02,
        -4.48380411e-02, -8.05420280e-02, -1.64255090e-02, -6.48153797e-02,
         5.06782858e-03, -2.43175868e-03, -5.40565178e-02, -8.12960323e-03,
         4.19079550e-02, -2.15617977e-02, -1.57967899e-02,  3.31747867e-02,
        -8.01364630e-02, -1.54114645e-02, -5.74465916e-02,  1.44828800e-02,
         3.75398025e-02, -9.97637808e-02, -8.92196968e-03, -6.80585429e-02,
         5.85166179e-02, -3.27327773e-02, -2.40229815e-03, -6.30820077e-03,
         4.79136705e-02, -8.28515515e-02, -2.71539204e-02, -4.32537962e-03,
         2.57454626e-02, -3.27682085e-02,  2.09330637e-02, -7.94779956e-02,
         1.91955678e-02, -1.16449185e-02,  9.50378273e-03, -4.35635038e-02,
        -3.66505533e-02, -9.70793366e-02,  8.94268136e-03, -1.46269398e-02,
         5.45645840e-02,  6.92141205e-02,  1.05012529e-01,  1.10859863e-01,
        -1.34864971e-02,  8.77503306e-03, -1.14638149e-03,  1.05595574e-01,
        -3.30545455e-02,  1.49801131e-02, -7.64260069e-02,  4.41715568e-02,
         8.06645304e-02,  3.79374810e-02, -1.73761696e-02,  4.10951860e-02,
        -2.40345821e-02, -4.80216332e-02,  1.50007065e-02,  3.03008184e-02,
         4.40813182e-03, -1.10763662e-01,  5.87851778e-02,  5.47064729e-02,
         8.96646827e-03, -4.55785692e-02, -4.77991328e-02,  8.83815959e-02,
        -1.86152197e-02,  2.07292549e-02, -2.19883397e-02,  7.60800242e-02,
         1.60371698e-02, -1.16604365e-01,  1.25039175e-01, -7.68837333e-03,
         3.03481687e-02, -1.52714243e-02, -6.32316470e-02, -2.49990914e-32,
        -8.10585022e-02, -5.51191568e-02, -1.33699374e-02, -5.99327907e-02,
         1.10146394e-02,  2.59977896e-02,  3.60030234e-02,  4.94830823e-03,
         1.81742699e-03, -7.88456202e-02, -5.46012409e-02, -3.52930427e-02,
        -6.31591398e-03,  6.83287606e-02,  1.65332407e-02, -8.12145397e-02,
         5.00030024e-03,  1.31413504e-01, -4.67872508e-02, -5.32843284e-02,
         6.42249063e-02, -5.45797981e-02, -4.81015742e-02,  2.70940475e-02,
         8.49387497e-02, -5.11573721e-03,  8.52151513e-02,  4.48351949e-02,
        -9.25949216e-02,  8.05962086e-03,  2.34439634e-02,  4.24520560e-02,
        -5.95207177e-02,  1.05523206e-02, -6.87899813e-02,  6.73937728e-04,
         4.62168045e-02, -6.29209820e-03,  3.83899324e-02,  2.46823020e-03,
        -9.38248113e-02,  5.74741922e-02,  7.89213926e-02, -2.18204875e-02,
        -4.18461375e-02, -5.63514344e-02, -4.13205549e-02,  2.18046643e-02,
        -9.33823735e-02,  3.08047123e-02, -6.42291158e-02, -1.99530181e-02,
         3.61034833e-02, -3.50957811e-02,  3.22241597e-02,  6.15459457e-02,
         5.70552759e-02,  1.59135945e-02, -2.45294087e-02,  9.99931172e-02,
         5.59420958e-02, -4.10363562e-02, -6.51614890e-02,  2.00892612e-02,
         4.90734093e-02,  3.07650082e-02, -5.85500784e-02, -5.81300771e-03,
         3.74068208e-02,  4.96497601e-02, -6.38446733e-02, -2.64048181e-03,
         5.88807538e-02, -4.38631549e-02,  6.60317093e-02, -7.83692077e-02,
         6.36432096e-02,  6.92372583e-03, -8.18328112e-02, -3.14817317e-02,
        -3.57160321e-03,  1.01911925e-01, -5.81695735e-02, -2.84043569e-02,
         1.21233733e-02,  2.11809226e-03, -4.04893272e-02, -5.31520881e-02,
        -1.43813621e-02,  3.91902626e-02, -4.59962897e-02, -2.05660868e-03,
         6.13806909e-03,  9.19523835e-02,  1.95201244e-02,  1.56344922e-32,
         2.62332484e-02,  9.64798480e-02, -6.58232719e-02,  4.79708761e-02,
         8.70390460e-02,  4.03306670e-02,  1.44300619e-02, -4.76207808e-02,
        -8.86879582e-03,  1.93301495e-02, -1.29634440e-02,  4.97946739e-02,
        -6.92615882e-02,  3.16581689e-02, -3.13160643e-02, -3.00069898e-02,
        -4.07419307e-03, -1.46255158e-02, -1.23310108e-02,  2.74193212e-02,
         8.34065378e-02,  6.97517619e-02, -1.05787523e-01,  8.78471509e-02,
         5.59022231e-03, -1.86682567e-02, -6.24801964e-02, -3.62294214e-03,
        -3.38804536e-02,  4.26130667e-02, -3.24046277e-02, -9.78929177e-02,
         1.34582929e-02,  4.51985709e-02, -4.52558734e-02, -1.61164999e-02,
         8.62949118e-02,  2.88819801e-02, -8.69680103e-03,  1.49755552e-01,
         3.60441841e-02,  2.37741750e-02, -3.88363563e-02,  5.74692935e-02,
        -2.12660152e-02, -4.92211245e-03, -7.09280139e-03, -5.32866456e-02,
        -8.20563585e-02,  4.31005657e-02, -3.67642939e-02, -2.71880608e-02,
        -1.35272205e-01, -2.56682355e-02, -2.91684028e-02, -8.94128382e-02,
         1.41426641e-02,  7.27050100e-03, -7.77576491e-02, -9.60375089e-03,
        -4.91312295e-02,  5.92100769e-02, -2.87621375e-02, -1.12884371e-02,
        -2.84832269e-02, -8.75013601e-03,  1.74761526e-02,  4.95308675e-02,
         3.17866504e-02,  3.20894495e-02, -8.73307511e-02, -7.09942076e-03,
         5.87638542e-02, -6.80810947e-04,  3.69722694e-02, -2.14159191e-02,
         9.13810582e-05, -1.07633816e-02, -5.68082258e-02, -2.79051326e-02,
        -1.05843894e-01, -9.68937122e-04,  1.14391567e-02, -9.73246060e-03,
        -4.10722606e-02,  3.72071378e-02,  4.89398278e-02,  4.51454930e-02,
         1.92308407e-02, -1.15436651e-02,  5.01300581e-03,  2.97262445e-02,
         6.92122579e-02,  1.63906328e-02,  8.69894680e-03, -4.69932573e-08,
         9.97944549e-03, -5.11729307e-02,  7.04230741e-02,  6.84352070e-02,
         3.95479538e-02,  1.35835100e-04, -7.60002732e-02,  4.00973707e-02,
        -3.73462401e-02, -5.88462828e-03,  1.22180901e-01,  8.05509184e-03,
        -1.34176323e-02,  1.23290345e-02,  2.55201720e-02,  1.09683396e-02,
         6.05740584e-04, -2.16496997e-02, -5.05289622e-02, -1.30557213e-02,
         1.05004385e-02,  1.00649591e-03, -3.34202051e-02, -1.19563006e-02,
         3.54323424e-02, -7.30695277e-02, -1.92586686e-02,  6.82983696e-02,
        -5.41707389e-02, -3.45373824e-02,  5.45379631e-02,  2.30299924e-02,
         1.27890641e-02,  2.67073419e-02,  2.77423747e-02,  1.66754276e-02,
        -9.89097822e-03, -1.50999101e-02,  1.57295670e-02,  1.33830905e-01,
         4.96073673e-03, -5.15581341e-03,  2.67172307e-02,  9.28953476e-03,
         5.75694405e-02, -3.65181193e-02, -1.39185563e-01, -5.01695983e-02,
         4.19336818e-02, -7.75045007e-02, -4.21275385e-02, -2.39884313e-02,
        -6.29835576e-02,  7.19864741e-02,  1.34467065e-01, -8.73645023e-03,
        -7.97666982e-03, -6.91410005e-02,  3.03546451e-02,  6.15585037e-02,
        -2.00266228e-03, -6.09333478e-02, -6.89558536e-02, -6.41390905e-02],
       dtype=float32)}

In [26]:
pages_and_chunk=[]
pages_and_chunk

[]

In [27]:
pages_and_chunk =pd.read_csv(page_and_Embedding_path)
data = pages_and_chunk.to_dict(orient="records")
data[5]

{'paragraphe': '4.5.3 Batch-Wise Load Balance VS.Sequence-Wise Load Balance . . . . . . . . .27 5 Post-Training 28 5.1 Supervised Fine-Tuning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .28 5.2 Reinforcement Learning . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.1 Reward Model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .29 5.2.2 Group Relative Policy Optimization . . . . . . . . . . . . . . . . . . . . . .30 5.3 Evaluations . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.1 Evaluation Settings . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30 5.3.2 Standard Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .31 5.3.3 Open-Ended Evaluation . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'word_count': 298,
 'char_count': 830,
 'tokens_count': 207,
 'sentence_count': 10,
 'page_number': 3,
 'embedding': '[-5.76342642e-02  1.86270513e-02 -6.96300939e-02 -5.02151484e-03\n -6.43548295e-02  5.39917722e-02 -4.61325161e-02  3.96140479e-02\n -5.72230071e-02  5.44097507e-03 -4.39483449e-02 -6.78690989e-03\n  4.00274098e-02 -1.59040969e-02  7.62041006e-03  4.98709492e-02\n  1.28310844e-01 -3.56771424e-02 -4.98869866e-02 -8.15588683e-02\n  4.34629619e-02 -4.59041297e-02  8.90599862e-02  1.54037271e-02\n -7.79619813e-02  3.06390580e-02 -5.25192842e-02 -6.64412901e-02\n  3.31790484e-02 -6.93642348e-02 -6.77236822e-03  3.17600835e-03\n  5.10904342e-02 -8.24809149e-02 -8.37938786e-02  1.99514590e-02\n -5.22203557e-02 -5.73823750e-02  1.78819466e-02  2.67784391e-02\n  1.22638667e-04 -3.79560366e-02  2.66230456e-03  2.12215632e-02\n  3.83331478e-02 -2.20189728e-02 -5.95768988e-02 -2.69228090e-02\n -4.48380411e-02 -8.05420280e-02 -1.64255090e-02 -6.48153797e-02\n  5.06782858e-03 -2.43175868e-03 -5.40565178e-02 -8.12960323e-03\n  4.19079550e-02 -2.15617977e-02 -1.57967899e-02  3.31747867e-02\n -8.01364630e-02 -1.54114645e-02 -5.74465916e-02  1.44828800e-02\n  3.75398025e-02 -9.97637808e-02 -8.92196968e-03 -6.80585429e-02\n  5.85166179e-02 -3.27327773e-02 -2.40229815e-03 -6.30820077e-03\n  4.79136705e-02 -8.28515515e-02 -2.71539204e-02 -4.32537962e-03\n  2.57454626e-02 -3.27682085e-02  2.09330637e-02 -7.94779956e-02\n  1.91955678e-02 -1.16449185e-02  9.50378273e-03 -4.35635038e-02\n -3.66505533e-02 -9.70793366e-02  8.94268136e-03 -1.46269398e-02\n  5.45645840e-02  6.92141205e-02  1.05012529e-01  1.10859863e-01\n -1.34864971e-02  8.77503306e-03 -1.14638149e-03  1.05595574e-01\n -3.30545455e-02  1.49801131e-02 -7.64260069e-02  4.41715568e-02\n  8.06645304e-02  3.79374810e-02 -1.73761696e-02  4.10951860e-02\n -2.40345821e-02 -4.80216332e-02  1.50007065e-02  3.03008184e-02\n  4.40813182e-03 -1.10763662e-01  5.87851778e-02  5.47064729e-02\n  8.96646827e-03 -4.55785692e-02 -4.77991328e-02  8.83815959e-02\n -1.86152197e-02  2.07292549e-02 -2.19883397e-02  7.60800242e-02\n  1.60371698e-02 -1.16604365e-01  1.25039175e-01 -7.68837333e-03\n  3.03481687e-02 -1.52714243e-02 -6.32316470e-02 -2.49990914e-32\n -8.10585022e-02 -5.51191568e-02 -1.33699374e-02 -5.99327907e-02\n  1.10146394e-02  2.59977896e-02  3.60030234e-02  4.94830823e-03\n  1.81742699e-03 -7.88456202e-02 -5.46012409e-02 -3.52930427e-02\n -6.31591398e-03  6.83287606e-02  1.65332407e-02 -8.12145397e-02\n  5.00030024e-03  1.31413504e-01 -4.67872508e-02 -5.32843284e-02\n  6.42249063e-02 -5.45797981e-02 -4.81015742e-02  2.70940475e-02\n  8.49387497e-02 -5.11573721e-03  8.52151513e-02  4.48351949e-02\n -9.25949216e-02  8.05962086e-03  2.34439634e-02  4.24520560e-02\n -5.95207177e-02  1.05523206e-02 -6.87899813e-02  6.73937728e-04\n  4.62168045e-02 -6.29209820e-03  3.83899324e-02  2.46823020e-03\n -9.38248113e-02  5.74741922e-02  7.89213926e-02 -2.18204875e-02\n -4.18461375e-02 -5.63514344e-02 -4.13205549e-02  2.18046643e-02\n -9.33823735e-02  3.08047123e-02 -6.42291158e-02 -1.99530181e-02\n  3.61034833e-02 -3.50957811e-02  3.22241597e-02  6.15459457e-02\n  5.70552759e-02  1.59135945e-02 -2.45294087e-02  9.99931172e-02\n  5.59420958e-02 -4.10363562e-02 -6.51614890e-02  2.00892612e-02\n  4.90734093e-02  3.07650082e-02 -5.85500784e-02 -5.81300771e-03\n  3.74068208e-02  4.96497601e-02 -6.38446733e-02 -2.64048181e-03\n  5.88807538e-02 -4.38631549e-02  6.60317093e-02 -7.83692077e-02\n  6.36432096e-02  6.92372583e-03 -8.18328112e-02 -3.14817317e-02\n -3.57160321e-03  1.01911925e-01 -5.81695735e-02 -2.84043569e-02\n  1.21233733e-02  2.11809226e-03 -4.04893272e-02 -5.31520881e-02\n -1.43813621e-02  3.91902626e-02 -4.59962897e-02 -2.05660868e-03\n  6.13806909e-03  9.19523835e-02  1.95201244e-02  1.56344922e-32\n  2.62332484e-02  9.64798480e-02 -6.58232719e-02  4.79708761e-02\n  8.70390460e-02  4.03306670e-02  1.44300619e-02 -4.76207808e-02\n -8.86879582e-03  1.93301495e-02 -1.29634440e-02  4.97946739e-02\n -6.92615882e-02  3.16581689e-02 -3.13160643e-02 -3.00069898e-02\n -4.07419307e-03 -1.46255158e-02 -1.23310108e-02  2.74193212e-02\n  8.34065378e-02  6.97517619e-02 -1.05787523e-01  8.78471509e-02\n  5.59022231e-03 -1.86682567e-02 -6.24801964e-02 -3.62294214e-03\n -3.38804536e-02  4.26130667e-02 -3.24046277e-02 -9.78929177e-02\n  1.34582929e-02  4.51985709e-02 -4.52558734e-02 -1.61164999e-02\n  8.62949118e-02  2.88819801e-02 -8.69680103e-03  1.49755552e-01\n  3.60441841e-02  2.37741750e-02 -3.88363563e-02  5.74692935e-02\n -2.12660152e-02 -4.92211245e-03 -7.09280139e-03 -5.32866456e-02\n -8.20563585e-02  4.31005657e-02 -3.67642939e-02 -2.71880608e-02\n -1.35272205e-01 -2.56682355e-02 -2.91684028e-02 -8.94128382e-02\n  1.41426641e-02  7.27050100e-03 -7.77576491e-02 -9.60375089e-03\n -4.91312295e-02  5.92100769e-02 -2.87621375e-02 -1.12884371e-02\n -2.84832269e-02 -8.75013601e-03  1.74761526e-02  4.95308675e-02\n  3.17866504e-02  3.20894495e-02 -8.73307511e-02 -7.09942076e-03\n  5.87638542e-02 -6.80810947e-04  3.69722694e-02 -2.14159191e-02\n  9.13810582e-05 -1.07633816e-02 -5.68082258e-02 -2.79051326e-02\n -1.05843894e-01 -9.68937122e-04  1.14391567e-02 -9.73246060e-03\n -4.10722606e-02  3.72071378e-02  4.89398278e-02  4.51454930e-02\n  1.92308407e-02 -1.15436651e-02  5.01300581e-03  2.97262445e-02\n  6.92122579e-02  1.63906328e-02  8.69894680e-03 -4.69932573e-08\n  9.97944549e-03 -5.11729307e-02  7.04230741e-02  6.84352070e-02\n  3.95479538e-02  1.35835100e-04 -7.60002732e-02  4.00973707e-02\n -3.73462401e-02 -5.88462828e-03  1.22180901e-01  8.05509184e-03\n -1.34176323e-02  1.23290345e-02  2.55201720e-02  1.09683396e-02\n  6.05740584e-04 -2.16496997e-02 -5.05289622e-02 -1.30557213e-02\n  1.05004385e-02  1.00649591e-03 -3.34202051e-02 -1.19563006e-02\n  3.54323424e-02 -7.30695277e-02 -1.92586686e-02  6.82983696e-02\n -5.41707389e-02 -3.45373824e-02  5.45379631e-02  2.30299924e-02\n  1.27890641e-02  2.67073419e-02  2.77423747e-02  1.66754276e-02\n -9.89097822e-03 -1.50999101e-02  1.57295670e-02  1.33830905e-01\n  4.96073673e-03 -5.15581341e-03  2.67172307e-02  9.28953476e-03\n  5.75694405e-02 -3.65181193e-02 -1.39185563e-01 -5.01695983e-02\n  4.19336818e-02 -7.75045007e-02 -4.21275385e-02 -2.39884313e-02\n -6.29835576e-02  7.19864741e-02  1.34467065e-01 -8.73645023e-03\n -7.97666982e-03 -6.91410005e-02  3.03546451e-02  6.15585037e-02\n -2.00266228e-03 -6.09333478e-02 -6.89558536e-02 -6.41390905e-02]'}

In [28]:
import torch
import numpy as np
import pandas as pd

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [29]:
data[5]['embedding']

'[-5.76342642e-02  1.86270513e-02 -6.96300939e-02 -5.02151484e-03\n -6.43548295e-02  5.39917722e-02 -4.61325161e-02  3.96140479e-02\n -5.72230071e-02  5.44097507e-03 -4.39483449e-02 -6.78690989e-03\n  4.00274098e-02 -1.59040969e-02  7.62041006e-03  4.98709492e-02\n  1.28310844e-01 -3.56771424e-02 -4.98869866e-02 -8.15588683e-02\n  4.34629619e-02 -4.59041297e-02  8.90599862e-02  1.54037271e-02\n -7.79619813e-02  3.06390580e-02 -5.25192842e-02 -6.64412901e-02\n  3.31790484e-02 -6.93642348e-02 -6.77236822e-03  3.17600835e-03\n  5.10904342e-02 -8.24809149e-02 -8.37938786e-02  1.99514590e-02\n -5.22203557e-02 -5.73823750e-02  1.78819466e-02  2.67784391e-02\n  1.22638667e-04 -3.79560366e-02  2.66230456e-03  2.12215632e-02\n  3.83331478e-02 -2.20189728e-02 -5.95768988e-02 -2.69228090e-02\n -4.48380411e-02 -8.05420280e-02 -1.64255090e-02 -6.48153797e-02\n  5.06782858e-03 -2.43175868e-03 -5.40565178e-02 -8.12960323e-03\n  4.19079550e-02 -2.15617977e-02 -1.57967899e-02  3.31747867e-02\n -8.01364630e-02 -1.54114645e-02 -5.74465916e-02  1.44828800e-02\n  3.75398025e-02 -9.97637808e-02 -8.92196968e-03 -6.80585429e-02\n  5.85166179e-02 -3.27327773e-02 -2.40229815e-03 -6.30820077e-03\n  4.79136705e-02 -8.28515515e-02 -2.71539204e-02 -4.32537962e-03\n  2.57454626e-02 -3.27682085e-02  2.09330637e-02 -7.94779956e-02\n  1.91955678e-02 -1.16449185e-02  9.50378273e-03 -4.35635038e-02\n -3.66505533e-02 -9.70793366e-02  8.94268136e-03 -1.46269398e-02\n  5.45645840e-02  6.92141205e-02  1.05012529e-01  1.10859863e-01\n -1.34864971e-02  8.77503306e-03 -1.14638149e-03  1.05595574e-01\n -3.30545455e-02  1.49801131e-02 -7.64260069e-02  4.41715568e-02\n  8.06645304e-02  3.79374810e-02 -1.73761696e-02  4.10951860e-02\n -2.40345821e-02 -4.80216332e-02  1.50007065e-02  3.03008184e-02\n  4.40813182e-03 -1.10763662e-01  5.87851778e-02  5.47064729e-02\n  8.96646827e-03 -4.55785692e-02 -4.77991328e-02  8.83815959e-02\n -1.86152197e-02  2.07292549e-02 -2.19883397e-02  7.60800242e-02\n  1.60371698e-02 -1.16604365e-01  1.25039175e-01 -7.68837333e-03\n  3.03481687e-02 -1.52714243e-02 -6.32316470e-02 -2.49990914e-32\n -8.10585022e-02 -5.51191568e-02 -1.33699374e-02 -5.99327907e-02\n  1.10146394e-02  2.59977896e-02  3.60030234e-02  4.94830823e-03\n  1.81742699e-03 -7.88456202e-02 -5.46012409e-02 -3.52930427e-02\n -6.31591398e-03  6.83287606e-02  1.65332407e-02 -8.12145397e-02\n  5.00030024e-03  1.31413504e-01 -4.67872508e-02 -5.32843284e-02\n  6.42249063e-02 -5.45797981e-02 -4.81015742e-02  2.70940475e-02\n  8.49387497e-02 -5.11573721e-03  8.52151513e-02  4.48351949e-02\n -9.25949216e-02  8.05962086e-03  2.34439634e-02  4.24520560e-02\n -5.95207177e-02  1.05523206e-02 -6.87899813e-02  6.73937728e-04\n  4.62168045e-02 -6.29209820e-03  3.83899324e-02  2.46823020e-03\n -9.38248113e-02  5.74741922e-02  7.89213926e-02 -2.18204875e-02\n -4.18461375e-02 -5.63514344e-02 -4.13205549e-02  2.18046643e-02\n -9.33823735e-02  3.08047123e-02 -6.42291158e-02 -1.99530181e-02\n  3.61034833e-02 -3.50957811e-02  3.22241597e-02  6.15459457e-02\n  5.70552759e-02  1.59135945e-02 -2.45294087e-02  9.99931172e-02\n  5.59420958e-02 -4.10363562e-02 -6.51614890e-02  2.00892612e-02\n  4.90734093e-02  3.07650082e-02 -5.85500784e-02 -5.81300771e-03\n  3.74068208e-02  4.96497601e-02 -6.38446733e-02 -2.64048181e-03\n  5.88807538e-02 -4.38631549e-02  6.60317093e-02 -7.83692077e-02\n  6.36432096e-02  6.92372583e-03 -8.18328112e-02 -3.14817317e-02\n -3.57160321e-03  1.01911925e-01 -5.81695735e-02 -2.84043569e-02\n  1.21233733e-02  2.11809226e-03 -4.04893272e-02 -5.31520881e-02\n -1.43813621e-02  3.91902626e-02 -4.59962897e-02 -2.05660868e-03\n  6.13806909e-03  9.19523835e-02  1.95201244e-02  1.56344922e-32\n  2.62332484e-02  9.64798480e-02 -6.58232719e-02  4.79708761e-02\n  8.70390460e-02  4.03306670e-02  1.44300619e-02 -4.76207808e-02\n -8.86879582e-03  1.93301495e-02 -1.29634440e-02  4.97946739e-02\n -6.92615882e-02  3.16581689e-02 -3.13160643e-02 -3.00069898e-02\n -4.07419307e-03 -1.46255158e-02 -1.23310108e-02  2.74193212e-02\n  8.34065378e-02  6.97517619e-02 -1.05787523e-01  8.78471509e-02\n  5.59022231e-03 -1.86682567e-02 -6.24801964e-02 -3.62294214e-03\n -3.38804536e-02  4.26130667e-02 -3.24046277e-02 -9.78929177e-02\n  1.34582929e-02  4.51985709e-02 -4.52558734e-02 -1.61164999e-02\n  8.62949118e-02  2.88819801e-02 -8.69680103e-03  1.49755552e-01\n  3.60441841e-02  2.37741750e-02 -3.88363563e-02  5.74692935e-02\n -2.12660152e-02 -4.92211245e-03 -7.09280139e-03 -5.32866456e-02\n -8.20563585e-02  4.31005657e-02 -3.67642939e-02 -2.71880608e-02\n -1.35272205e-01 -2.56682355e-02 -2.91684028e-02 -8.94128382e-02\n  1.41426641e-02  7.27050100e-03 -7.77576491e-02 -9.60375089e-03\n -4.91312295e-02  5.92100769e-02 -2.87621375e-02 -1.12884371e-02\n -2.84832269e-02 -8.75013601e-03  1.74761526e-02  4.95308675e-02\n  3.17866504e-02  3.20894495e-02 -8.73307511e-02 -7.09942076e-03\n  5.87638542e-02 -6.80810947e-04  3.69722694e-02 -2.14159191e-02\n  9.13810582e-05 -1.07633816e-02 -5.68082258e-02 -2.79051326e-02\n -1.05843894e-01 -9.68937122e-04  1.14391567e-02 -9.73246060e-03\n -4.10722606e-02  3.72071378e-02  4.89398278e-02  4.51454930e-02\n  1.92308407e-02 -1.15436651e-02  5.01300581e-03  2.97262445e-02\n  6.92122579e-02  1.63906328e-02  8.69894680e-03 -4.69932573e-08\n  9.97944549e-03 -5.11729307e-02  7.04230741e-02  6.84352070e-02\n  3.95479538e-02  1.35835100e-04 -7.60002732e-02  4.00973707e-02\n -3.73462401e-02 -5.88462828e-03  1.22180901e-01  8.05509184e-03\n -1.34176323e-02  1.23290345e-02  2.55201720e-02  1.09683396e-02\n  6.05740584e-04 -2.16496997e-02 -5.05289622e-02 -1.30557213e-02\n  1.05004385e-02  1.00649591e-03 -3.34202051e-02 -1.19563006e-02\n  3.54323424e-02 -7.30695277e-02 -1.92586686e-02  6.82983696e-02\n -5.41707389e-02 -3.45373824e-02  5.45379631e-02  2.30299924e-02\n  1.27890641e-02  2.67073419e-02  2.77423747e-02  1.66754276e-02\n -9.89097822e-03 -1.50999101e-02  1.57295670e-02  1.33830905e-01\n  4.96073673e-03 -5.15581341e-03  2.67172307e-02  9.28953476e-03\n  5.75694405e-02 -3.65181193e-02 -1.39185563e-01 -5.01695983e-02\n  4.19336818e-02 -7.75045007e-02 -4.21275385e-02 -2.39884313e-02\n -6.29835576e-02  7.19864741e-02  1.34467065e-01 -8.73645023e-03\n -7.97666982e-03 -6.91410005e-02  3.03546451e-02  6.15585037e-02\n -2.00266228e-03 -6.09333478e-02 -6.89558536e-02 -6.41390905e-02]'

* the data her is not in list shape so try to fix it

In [30]:
embedding = np.fromstring(data[5]['embedding'].strip('[]'), sep=' ')
embedding

array([-5.76342642e-02,  1.86270513e-02, -6.96300939e-02, -5.02151484e-03,
       -6.43548295e-02,  5.39917722e-02, -4.61325161e-02,  3.96140479e-02,
       -5.72230071e-02,  5.44097507e-03, -4.39483449e-02, -6.78690989e-03,
        4.00274098e-02, -1.59040969e-02,  7.62041006e-03,  4.98709492e-02,
        1.28310844e-01, -3.56771424e-02, -4.98869866e-02, -8.15588683e-02,
        4.34629619e-02, -4.59041297e-02,  8.90599862e-02,  1.54037271e-02,
       -7.79619813e-02,  3.06390580e-02, -5.25192842e-02, -6.64412901e-02,
        3.31790484e-02, -6.93642348e-02, -6.77236822e-03,  3.17600835e-03,
        5.10904342e-02, -8.24809149e-02, -8.37938786e-02,  1.99514590e-02,
       -5.22203557e-02, -5.73823750e-02,  1.78819466e-02,  2.67784391e-02,
        1.22638667e-04, -3.79560366e-02,  2.66230456e-03,  2.12215632e-02,
        3.83331478e-02, -2.20189728e-02, -5.95768988e-02, -2.69228090e-02,
       -4.48380411e-02, -8.05420280e-02, -1.64255090e-02, -6.48153797e-02,
        5.06782858e-03, -2.43175868e-03, -5.40565178e-02, -8.12960323e-03,
        4.19079550e-02, -2.15617977e-02, -1.57967899e-02,  3.31747867e-02,
       -8.01364630e-02, -1.54114645e-02, -5.74465916e-02,  1.44828800e-02,
        3.75398025e-02, -9.97637808e-02, -8.92196968e-03, -6.80585429e-02,
        5.85166179e-02, -3.27327773e-02, -2.40229815e-03, -6.30820077e-03,
        4.79136705e-02, -8.28515515e-02, -2.71539204e-02, -4.32537962e-03,
        2.57454626e-02, -3.27682085e-02,  2.09330637e-02, -7.94779956e-02,
        1.91955678e-02, -1.16449185e-02,  9.50378273e-03, -4.35635038e-02,
       -3.66505533e-02, -9.70793366e-02,  8.94268136e-03, -1.46269398e-02,
        5.45645840e-02,  6.92141205e-02,  1.05012529e-01,  1.10859863e-01,
       -1.34864971e-02,  8.77503306e-03, -1.14638149e-03,  1.05595574e-01,
       -3.30545455e-02,  1.49801131e-02, -7.64260069e-02,  4.41715568e-02,
        8.06645304e-02,  3.79374810e-02, -1.73761696e-02,  4.10951860e-02,
       -2.40345821e-02, -4.80216332e-02,  1.50007065e-02,  3.03008184e-02,
        4.40813182e-03, -1.10763662e-01,  5.87851778e-02,  5.47064729e-02,
        8.96646827e-03, -4.55785692e-02, -4.77991328e-02,  8.83815959e-02,
       -1.86152197e-02,  2.07292549e-02, -2.19883397e-02,  7.60800242e-02,
        1.60371698e-02, -1.16604365e-01,  1.25039175e-01, -7.68837333e-03,
        3.03481687e-02, -1.52714243e-02, -6.32316470e-02, -2.49990914e-32,
       -8.10585022e-02, -5.51191568e-02, -1.33699374e-02, -5.99327907e-02,
        1.10146394e-02,  2.59977896e-02,  3.60030234e-02,  4.94830823e-03,
        1.81742699e-03, -7.88456202e-02, -5.46012409e-02, -3.52930427e-02,
       -6.31591398e-03,  6.83287606e-02,  1.65332407e-02, -8.12145397e-02,
        5.00030024e-03,  1.31413504e-01, -4.67872508e-02, -5.32843284e-02,
        6.42249063e-02, -5.45797981e-02, -4.81015742e-02,  2.70940475e-02,
        8.49387497e-02, -5.11573721e-03,  8.52151513e-02,  4.48351949e-02,
       -9.25949216e-02,  8.05962086e-03,  2.34439634e-02,  4.24520560e-02,
       -5.95207177e-02,  1.05523206e-02, -6.87899813e-02,  6.73937728e-04,
        4.62168045e-02, -6.29209820e-03,  3.83899324e-02,  2.46823020e-03,
       -9.38248113e-02,  5.74741922e-02,  7.89213926e-02, -2.18204875e-02,
       -4.18461375e-02, -5.63514344e-02, -4.13205549e-02,  2.18046643e-02,
       -9.33823735e-02,  3.08047123e-02, -6.42291158e-02, -1.99530181e-02,
        3.61034833e-02, -3.50957811e-02,  3.22241597e-02,  6.15459457e-02,
        5.70552759e-02,  1.59135945e-02, -2.45294087e-02,  9.99931172e-02,
        5.59420958e-02, -4.10363562e-02, -6.51614890e-02,  2.00892612e-02,
        4.90734093e-02,  3.07650082e-02, -5.85500784e-02, -5.81300771e-03,
        3.74068208e-02,  4.96497601e-02, -6.38446733e-02, -2.64048181e-03,
        5.88807538e-02, -4.38631549e-02,  6.60317093e-02, -7.83692077e-02,
        6.36432096e-02,  6.92372583e-03, -8.18328112e-02, -3.14817317e-02,
       -3.57160321e-03,  1.01911925e-01, -5.81695735e-02, -2.84043569e-02,
        1.21233733e-02,  2.11809226e-03, -4.04893272e-02, -5.31520881e-02,
       -1.43813621e-02,  3.91902626e-02, -4.59962897e-02, -2.05660868e-03,
        6.13806909e-03,  9.19523835e-02,  1.95201244e-02,  1.56344922e-32,
        2.62332484e-02,  9.64798480e-02, -6.58232719e-02,  4.79708761e-02,
        8.70390460e-02,  4.03306670e-02,  1.44300619e-02, -4.76207808e-02,
       -8.86879582e-03,  1.93301495e-02, -1.29634440e-02,  4.97946739e-02,
       -6.92615882e-02,  3.16581689e-02, -3.13160643e-02, -3.00069898e-02,
       -4.07419307e-03, -1.46255158e-02, -1.23310108e-02,  2.74193212e-02,
        8.34065378e-02,  6.97517619e-02, -1.05787523e-01,  8.78471509e-02,
        5.59022231e-03, -1.86682567e-02, -6.24801964e-02, -3.62294214e-03,
       -3.38804536e-02,  4.26130667e-02, -3.24046277e-02, -9.78929177e-02,
        1.34582929e-02,  4.51985709e-02, -4.52558734e-02, -1.61164999e-02,
        8.62949118e-02,  2.88819801e-02, -8.69680103e-03,  1.49755552e-01,
        3.60441841e-02,  2.37741750e-02, -3.88363563e-02,  5.74692935e-02,
       -2.12660152e-02, -4.92211245e-03, -7.09280139e-03, -5.32866456e-02,
       -8.20563585e-02,  4.31005657e-02, -3.67642939e-02, -2.71880608e-02,
       -1.35272205e-01, -2.56682355e-02, -2.91684028e-02, -8.94128382e-02,
        1.41426641e-02,  7.27050100e-03, -7.77576491e-02, -9.60375089e-03,
       -4.91312295e-02,  5.92100769e-02, -2.87621375e-02, -1.12884371e-02,
       -2.84832269e-02, -8.75013601e-03,  1.74761526e-02,  4.95308675e-02,
        3.17866504e-02,  3.20894495e-02, -8.73307511e-02, -7.09942076e-03,
        5.87638542e-02, -6.80810947e-04,  3.69722694e-02, -2.14159191e-02,
        9.13810582e-05, -1.07633816e-02, -5.68082258e-02, -2.79051326e-02,
       -1.05843894e-01, -9.68937122e-04,  1.14391567e-02, -9.73246060e-03,
       -4.10722606e-02,  3.72071378e-02,  4.89398278e-02,  4.51454930e-02,
        1.92308407e-02, -1.15436651e-02,  5.01300581e-03,  2.97262445e-02,
        6.92122579e-02,  1.63906328e-02,  8.69894680e-03, -4.69932573e-08,
        9.97944549e-03, -5.11729307e-02,  7.04230741e-02,  6.84352070e-02,
        3.95479538e-02,  1.35835100e-04, -7.60002732e-02,  4.00973707e-02,
       -3.73462401e-02, -5.88462828e-03,  1.22180901e-01,  8.05509184e-03,
       -1.34176323e-02,  1.23290345e-02,  2.55201720e-02,  1.09683396e-02,
        6.05740584e-04, -2.16496997e-02, -5.05289622e-02, -1.30557213e-02,
        1.05004385e-02,  1.00649591e-03, -3.34202051e-02, -1.19563006e-02,
        3.54323424e-02, -7.30695277e-02, -1.92586686e-02,  6.82983696e-02,
       -5.41707389e-02, -3.45373824e-02,  5.45379631e-02,  2.30299924e-02,
        1.27890641e-02,  2.67073419e-02,  2.77423747e-02,  1.66754276e-02,
       -9.89097822e-03, -1.50999101e-02,  1.57295670e-02,  1.33830905e-01,
        4.96073673e-03, -5.15581341e-03,  2.67172307e-02,  9.28953476e-03,
        5.75694405e-02, -3.65181193e-02, -1.39185563e-01, -5.01695983e-02,
        4.19336818e-02, -7.75045007e-02, -4.21275385e-02, -2.39884313e-02,
       -6.29835576e-02,  7.19864741e-02,  1.34467065e-01, -8.73645023e-03,
       -7.97666982e-03, -6.91410005e-02,  3.03546451e-02,  6.15585037e-02,
       -2.00266228e-03, -6.09333478e-02, -6.89558536e-02, -6.41390905e-02])

In [31]:
for item in data:
    item['embedding'] = np.fromstring(item['embedding'].strip('[]'), sep=' ')

In [32]:
embeddings=[item["embedding"] for item in data]
embeddings

[array([-7.36545101e-02, -5.92405535e-02,  5.75507917e-02,  7.15857446e-02,
         1.54401911e-02, -1.63372289e-02, -7.57387280e-02, -7.95286731e-04,
        -2.40841825e-02, -6.18494526e-02, -1.24292113e-01, -1.00587502e-01,
        -2.54351702e-02, -4.82992306e-02,  1.18151614e-02,  2.85590384e-02,
         5.89606017e-02,  6.40023202e-02, -1.25724912e-01, -8.45907107e-02,
         2.48465836e-02,  1.34899113e-02,  5.55628873e-02, -2.93894038e-02,
         2.66428962e-02,  5.07843122e-02, -1.18925818e-03, -1.09014049e-01,
         1.42405117e-02, -6.30987585e-02,  4.47497256e-02, -3.49189080e-02,
         3.93743142e-02,  1.80438850e-02, -4.82038371e-02,  1.15270421e-01,
        -1.40792429e-01, -8.29446614e-02,  3.17647830e-02, -6.87950104e-02,
         2.28424696e-03,  1.05707943e-02, -1.77034661e-02,  6.14538342e-02,
         5.65049760e-02,  5.83483316e-02,  3.36036533e-02, -7.81908631e-02,
         4.88184020e-02, -2.30751317e-02, -6.04354627e-02, -8.41500908e-02,
         4.49782461e-02,  5.46326153e-02, -5.16212285e-02,  7.21360906e-04,
         4.17707264e-02,  2.89894994e-02,  5.72450459e-03,  3.40614133e-02,
        -1.68882925e-02, -9.43698063e-02,  4.41695144e-03, -5.72452508e-02,
         6.95676869e-03, -4.72279489e-02,  5.50259138e-03,  4.24455032e-02,
        -2.06548180e-02,  4.80773626e-03,  4.01677238e-03,  1.35990873e-01,
        -1.70332361e-02, -5.26663195e-03, -5.73401386e-03,  9.73371193e-02,
         7.63155073e-02,  2.71089356e-02,  1.15384966e-01, -8.60132724e-02,
         6.24588877e-03, -1.76614746e-02,  1.49291661e-02, -3.23114321e-02,
         1.20315783e-01, -1.37790041e-02, -8.84563848e-03,  2.89110243e-02,
        -3.97716239e-02,  3.87413390e-02, -4.51677851e-02, -1.99127197e-02,
         7.55467117e-02, -1.02538932e-02,  5.05393073e-02,  7.40994066e-02,
        -5.52553013e-02, -8.12891349e-02, -1.27333492e-01,  9.85729247e-02,
        -3.42265610e-03,  7.89162144e-02,  7.80439898e-02,  1.86082721e-02,
         1.12325568e-02, -1.78675018e-02,  4.59726714e-02, -6.15691068e-04,
         2.82680131e-02,  4.67756623e-03,  6.36407286e-02,  5.93631975e-02,
         9.21989679e-02, -1.61985736e-02, -1.96268968e-02,  6.67901859e-02,
        -5.10301068e-02, -4.22006696e-02, -8.15443788e-03,  8.30097869e-02,
        -4.52640317e-02, -2.43692156e-02, -7.55408779e-03, -4.52205203e-02,
        -2.43633147e-03, -1.28824878e-02, -2.17346475e-02,  4.66412502e-33,
        -1.92291476e-02,  3.38960253e-02,  3.02155968e-02, -4.38047163e-02,
         8.15873872e-03, -4.60115448e-02, -5.31847868e-03,  3.41555364e-02,
        -6.64872304e-02, -2.31052544e-02, -2.03916319e-02, -1.87412165e-02,
        -6.49015456e-02,  1.46500811e-01, -1.07832355e-02, -2.74298862e-02,
        -3.59992459e-02,  6.53540045e-02, -2.21363008e-02, -8.84282228e-04,
         7.90865645e-02, -3.85905169e-02, -6.55979514e-02, -6.07736148e-02,
         3.70096904e-03, -7.66620785e-03,  9.32073668e-02, -6.14669584e-02,
        -6.73091412e-03,  1.01368269e-02, -1.30949438e-01, -3.43734138e-02,
        -2.12248862e-02,  4.29290570e-02,  1.55341523e-02, -5.71324788e-02,
        -2.98370514e-02, -4.55813110e-02, -6.02533156e-03, -1.21637676e-02,
         4.42576921e-03,  6.30749539e-02,  1.62854400e-02, -2.60945149e-02,
        -8.20358545e-02, -5.87974340e-02,  3.03448900e-03, -2.76656114e-02,
        -2.90018488e-02,  8.78179818e-03,  1.61610339e-02, -3.56828533e-02,
        -2.37761140e-02, -5.01886159e-02,  3.18017937e-02, -3.44655998e-02,
         5.44531457e-02,  9.16673690e-02,  4.57444452e-02,  3.14397998e-02,
         7.44727300e-03,  2.81543545e-02,  1.57230385e-02,  1.13029666e-01,
         8.45999271e-03,  6.37475997e-02, -9.57024191e-03,  1.46056026e-01,
         1.61169805e-02,  2.47888509e-02, -8.02993192e-04,  1.64082423e-02,
         3.95082682e-02, -2.65461765e-02, -6.04664534e-03,  1.16666434e-02,
         4.71574217e-02, -1.01466395e-01,  1.52230971e-02,  3.13782766e-02,
         1.87016241e-02,  6.05213456e-02, -2.29711905e-02,  2.80696489e-02,
        -1.19734174e-02, -3.50229442e-02,  6.42543240e-03, -8.83941129e-02,
         1.88682806e-02,  1.53512871e-02, -2.00651754e-02, -4.57690842e-02,
        -3.07951421e-02, -2.99285073e-03, -7.25532025e-02, -2.80538357e-33,
        -1.79780211e-04,  6.79054111e-02, -4.98998240e-02,  6.09748289e-02,
        -3.32329907e-02, -1.72712114e-02, -4.13232371e-02,  5.03200851e-02,
        -6.12706877e-02,  1.30293407e-02,  8.57344549e-03, -2.62614582e-02,
         6.47765696e-02, -2.39429623e-02,  6.25177696e-02, -1.66653823e-02,
        -2.22485755e-02,  8.12776946e-03,  1.64038669e-02, -1.03466781e-02,
         3.06867752e-02,  6.58851862e-02, -7.84938112e-02,  6.46218434e-02,
        -4.69758287e-02, -1.86146647e-02, -5.43937124e-02,  7.00666234e-02,
        -5.85723156e-03, -1.42591465e-02, -5.12143224e-03, -1.62344724e-02,
        -2.01102719e-02,  3.34333181e-02, -1.92594379e-02,  3.36539447e-02,
         6.61960840e-02, -1.80941802e-02, -1.77126154e-02,  3.14082541e-02,
         1.13496073e-01, -5.68226166e-02, -1.65281724e-02,  2.57995147e-02,
        -1.08513087e-01,  1.69489831e-02, -5.26489802e-02, -4.25187461e-02,
        -4.67190892e-03,  1.56408977e-02, -2.20717844e-02, -7.89547060e-03,
        -8.79504532e-02, -1.41685363e-03, -7.41648823e-02, -6.89151809e-02,
         1.32032193e-03,  7.18301255e-03,  4.22402620e-02, -1.29507231e-02,
        -5.94598837e-02, -2.15145014e-02,  4.72501665e-02, -4.47048061e-02,
         1.82686392e-02, -3.41442823e-02, -2.28104554e-02,  3.97904292e-02,
         2.98106037e-02, -1.37344999e-02,  1.47425421e-02, -8.66571907e-03,
         6.74800202e-02,  9.42610428e-02, -6.54761493e-03,  6.23168200e-02,
         5.53143881e-02, -7.30767474e-02, -1.26313902e-02, -3.48972790e-02,
         3.29144532e-03,  1.93192456e-02, -5.01440652e-03,  4.39123586e-02,
         6.30708486e-02,  7.76557177e-02,  1.89033523e-02,  6.32455647e-02,
        -2.61266194e-02,  4.19540294e-02, -6.05345368e-02,  5.59334643e-02,
        -4.70450148e-02,  1.07230477e-01, -4.37842235e-02, -4.39244445e-08,
        -4.54436913e-02,  5.85300773e-02,  3.94488201e-02,  3.78575847e-02,
         1.00979973e-02, -7.13360235e-02, -2.50397958e-02,  9.42401737e-02,
        -4.34387801e-03,  4.68532145e-02,  9.48943570e-02, -1.58426464e-02,
        -5.22853881e-02, -6.73166960e-02,  2.37377398e-02,  6.27047047e-02,
         2.45904569e-02,  1.48554081e-02, -7.40337605e-03, -5.34284934e-02,
         6.22454993e-02,  4.06175442e-02,  7.12228939e-02, -7.54844695e-02,
         5.87192699e-02, -7.54838064e-02, -2.89883893e-02,  8.29493552e-02,
        -1.11948792e-02, -3.05846762e-02,  6.50292204e-04,  2.79335342e-02,
        -2.71967314e-02, -9.44096223e-02,  2.87864897e-02,  1.28622815e-01,
        -2.21352912e-02, -2.42820401e-02,  5.68571128e-02, -2.05320166e-03,
         2.89760754e-02,  1.02703810e-01, -2.61279773e-02,  1.42625710e-02,
        -1.83888730e-02, -6.10387279e-03, -5.25135919e-02, -4.78076078e-02,
         5.91903254e-02, -3.91051918e-02, -7.87664857e-03,  5.99237997e-03,
         1.03719635e-02,  9.41201523e-02,  2.99628228e-02,  5.04732653e-02,
        -3.61868516e-02, -1.43785554e-03,  3.96512710e-02,  5.43301404e-02,
         6.14602715e-02, -7.25980103e-02, -4.58648019e-02,  2.27012802e-02]),
 array([-1.14521928e-01,  7.90135004e-03, -7.34651685e-02,  3.13613676e-02,
         2.16853488e-02, -5.83156310e-02,  1.58812590e-02, -2.72330754e-02,
        -1.13712117e-01, -6.55378914e-03, -8.49533943e-04, -5.58769656e-03,
         1.67666413e-02, -2.13291906e-02, -1.26991257e-01, -8.52217432e-03,
        -1.12560593e-01, -1.15131490e-01,  6.56480193e-02, -7.28065241e-03,
        -3.49060707e-02,  4.19288054e-02, -2.20058560e-02,  5.87667478e-03,
        -8.49315722e-04,  2.06239894e-03, -2.29054186e-02,  4.58148047e-02,
        -1.91787295e-02, -1.20298982e-01,  3.31707262e-02,  7.09628016e-02,
        -1.77347120e-02, -1.78957060e-02,  7.57021755e-02,  6.73394129e-02,
         2.93627512e-02,  1.29727591e-02, -2.32237764e-03, -3.92797776e-02,
         5.91745088e-03, -7.69666508e-02,  5.19315079e-02,  6.93272650e-02,
         2.51195636e-02,  5.81528954e-02,  2.31369473e-02, -3.75789180e-02,
        -2.82935128e-02,  9.48016346e-02, -6.43884763e-02,  1.41074555e-02,
         2.85122525e-02, -1.70723386e-02,  5.88897876e-02, -5.12493737e-02,
        -5.29041793e-03, -3.69138122e-02, -9.72594321e-03, -7.76582658e-02,
         6.57883286e-02, -1.43246707e-02, -8.34956318e-02, -2.51432192e-02,
        -6.36166856e-02, -2.39132140e-02,  1.24855064e-01, -8.81804503e-04,
         2.04717666e-02,  1.67688970e-02,  2.40080501e-03,  9.37746763e-02,
        -4.71508279e-02,  8.29049759e-03,  4.37057801e-02,  4.16780189e-02,
         3.10722459e-02, -9.23381299e-02,  1.20536476e-01, -1.68706700e-01,
        -1.57722144e-03, -5.06318733e-02,  1.23326071e-02,  5.89367002e-02,
         1.47082452e-02,  1.98826324e-02, -4.56486084e-02,  3.49411368e-02,
         7.70492256e-02, -5.22322282e-02,  9.20494087e-03, -1.27681484e-02,
         7.40752965e-02,  2.94319671e-02,  7.59766623e-03,  4.75656018e-02,
         7.71161839e-02, -3.59194987e-02, -1.75121408e-02,  9.10691246e-02,
         5.34711890e-02, -4.45894897e-02, -3.64287831e-02,  3.72273587e-02,
         1.46583319e-02,  5.28312847e-03,  4.00658622e-02,  3.04541737e-02,
        -5.08740507e-02, -4.20135893e-02, -2.00043805e-02,  2.10384205e-02,
         7.58733135e-03, -8.40534195e-02,  1.17242383e-02,  7.67138451e-02,
        -2.83231176e-02,  1.73959024e-02, -5.65249249e-02, -2.67434642e-02,
        -6.72518313e-02,  3.46088111e-02, -8.14321339e-02,  3.59775126e-03,
        -5.94548844e-02, -1.29957311e-02,  4.68543470e-02,  3.11075368e-33,
        -5.24419174e-02, -2.59196833e-02, -5.06777205e-02,  1.08582325e-01,
         3.43738981e-02, -1.84982996e-02,  3.43601853e-02, -5.42532429e-02,
        -7.28169903e-02, -2.47531533e-02, -1.14516087e-01, -5.79711050e-02,
         2.35516950e-02,  2.57022940e-02,  3.65344249e-02, -6.65363967e-02,
        -1.37150632e-02,  4.50751744e-02, -5.05846739e-02, -3.41725983e-02,
         1.90298893e-02, -5.94473109e-02, -9.11915228e-02, -5.22501171e-02,
         6.10001087e-02,  7.91333169e-02,  2.17660498e-02, -2.02539451e-02,
         4.57969941e-02,  4.87441160e-02,  6.26598671e-02,  4.08577509e-02,
         7.47625809e-03,  1.30898310e-02,  4.90898453e-02, -1.52359800e-02,
        -5.16297854e-02,  1.33300619e-03, -5.38349710e-02, -3.61093767e-02,
         5.13958335e-02,  9.34072137e-02, -5.75774647e-02, -4.01219092e-02,
         2.73893308e-02, -5.07439934e-02,  4.01816182e-02,  3.62771600e-02,
         5.82200214e-02,  6.00221679e-02, -5.73248081e-02,  3.19686458e-02,
         7.80629041e-03, -3.03195417e-02, -4.73756372e-04,  3.21669616e-02,
         2.04291232e-02,  1.25583895e-02,  2.65230611e-02, -8.62162933e-03,
         8.08330625e-02,  8.04162472e-02,  7.64015829e-03,  1.65241247e-03,
        -4.43331385e-03,  2.54183561e-02,  4.02044430e-02, -1.40620843e-02,
         4.28878479e-02,  3.60292476e-03, -5.07352501e-02,  2.66947486e-02,
         2.39245445e-02, -9.23289806e-02,  7.27571473e-02, -2.10034102e-02,
        -3.20199654e-02, -2.62820348e-02,  1.31030902e-02, -4.48081344e-02,
        -1.59404799e-01,  1.33111523e-02,  1.58001687e-02,  1.80206690e-02,
        -1.70703977e-02, -5.13760373e-02,  1.94990076e-02,  3.23184277e-03,
        -4.02095430e-02,  1.21479100e-02,  1.28566325e-02, -4.88763265e-02,
        -8.99903418e-04, -7.26072863e-03, -4.10947204e-02, -2.72177415e-33,
         3.37950587e-02,  4.30003069e-02, -2.54120156e-02,  5.37003344e-03,
        -8.00439343e-02, -3.78511124e-03,  9.27126314e-03,  4.82315160e-02,
        -5.18373586e-02,  8.50481912e-03,  7.77947828e-02,  6.02789558e-02,
         4.45943400e-02,  3.17270383e-02, -1.82981312e-03, -4.71376721e-03,
         2.53879298e-02, -4.47602049e-02,  2.42201295e-02,  1.23118171e-02,
        -3.71463224e-02,  1.38965836e-02, -1.50949117e-02, -1.61212087e-02,
        -3.78416926e-02,  7.27905259e-02,  1.08641647e-01, -2.94866562e-02,
         3.82295373e-04,  9.70164197e-04, -5.21494038e-02, -6.33745790e-02,
        -7.19366297e-02,  3.78357209e-02,  8.06182902e-03, -2.40225270e-02,
         1.84199661e-01, -1.63553879e-02, -9.56168175e-02, -1.02062486e-01,
         4.51718196e-02,  7.98871443e-02, -5.95463514e-02,  7.67816007e-02,
         2.65228730e-02,  2.38523744e-02,  7.98063353e-02,  2.25182832e-03,
         3.20168883e-02, -1.03166863e-01,  4.97276010e-03, -5.72818816e-02,
         5.50791621e-02,  5.32983392e-02,  2.28819419e-02,  1.23271160e-02,
        -1.90460049e-02,  4.86444198e-02,  1.18935378e-02, -2.36965157e-02,
        -1.63988974e-02,  3.45184319e-02, -6.09933026e-02,  1.96206905e-02,
         5.12631424e-02, -2.73195677e-03, -3.09042018e-02,  7.04135522e-02,
        -1.93130728e-02, -9.11993533e-02,  3.80249545e-02,  2.77512688e-02,
        -5.17711639e-02, -1.73085034e-02, -1.54165132e-02, -4.55113202e-02,
         4.05072980e-02,  2.13369355e-02,  2.84439302e-03, -2.47022286e-02,
         2.74098516e-02, -2.14135442e-02, -4.79996428e-02,  1.06791206e-01,
        -5.22234477e-02, -2.28255056e-03,  3.55023257e-02,  3.32866460e-02,
         5.57103269e-02, -1.32941585e-02, -5.01564145e-02,  3.50137874e-02,
        -1.67549308e-02, -1.26585923e-02,  2.49192845e-02, -2.90612459e-08,
         2.47945823e-02,  1.33275285e-01, -5.36851808e-02, -1.08191958e-02,
        -2.94857323e-02,  5.80754429e-02, -7.00118542e-02, -7.82103091e-03,
         2.62094755e-02,  4.16846238e-02,  2.78528146e-02,  1.62595641e-02,
         4.11303788e-02, -1.16744749e-02,  3.24816653e-03, -7.11077033e-03,
        -1.05787836e-01,  8.91841669e-03, -4.37302552e-02, -6.95155263e-02,
         1.79326476e-03,  1.81078799e-02,  7.15545192e-02, -2.84759495e-02,
         1.00751314e-03,  2.28697229e-02,  4.35691932e-03, -6.01860322e-02,
         1.84260663e-02, -3.85510437e-02, -1.83013994e-02,  8.70772749e-02,
        -2.69840844e-02, -4.48351800e-02,  1.23093324e-02,  7.25843161e-02,
        -1.56508256e-02,  4.38426174e-02,  8.22704881e-02, -6.50408212e-03,
        -2.16607284e-02,  4.47601564e-02, -5.65633886e-02,  3.48572508e-02,
         4.33957800e-02,  4.45255488e-02, -3.00301313e-02, -8.56724679e-02,
         1.77508313e-02, -1.07550673e-01, -1.92638580e-02, -4.47204486e-02,
         8.48933011e-02,  2.81044450e-02, -3.29713859e-02,  6.73989654e-02,
        -4.35747840e-02, -3.50436531e-02,  6.12366796e-02,  5.95407300e-02,
         1.43924043e-01,  5.05437702e-03, -9.88887697e-02,  5.47500178e-02]),
 array([-1.76019724e-02, -5.03365993e-02, -4.91420552e-02, -2.67865285e-02,
        -2.11639628e-02, -3.51148248e-02, -2.85750329e-02,  7.06636235e-02,
        -8.06429386e-02, -3.10145188e-02, -1.25572354e-01, -8.18972513e-02,
         6.26901388e-02, -1.06560595e-01,  1.71216391e-02,  2.10714471e-02,
         4.85191718e-02, -1.09883407e-02, -6.04407527e-02, -7.21042901e-02,
         2.87862606e-02,  5.78067312e-03, -2.71266233e-02, -8.43138099e-02,
        -1.65598579e-02,  1.36788618e-02,  3.34896799e-03, -7.38364384e-02,
         2.32743621e-02, -2.26950720e-02,  2.17097942e-02,  3.66064198e-02,
        -1.33339697e-02,  3.47881764e-02, -7.52905756e-02,  6.21431135e-02,
        -3.14933397e-02, -8.83233026e-02, -5.61803542e-02, -2.10756455e-02,
        -3.75674702e-02, -3.35874967e-02, -7.13374838e-02,  2.97987112e-03,
         1.51336771e-02, -2.02295221e-02, -3.26654650e-02, -5.82190491e-02,
        -2.30376273e-02, -6.78526312e-02, -6.18188903e-02, -9.60645229e-02,
         2.73446608e-02,  6.65326118e-02, -1.00979879e-01,  9.28767677e-03,
        -9.41893551e-03, -2.10380927e-02, -4.72933389e-02,  2.14503463e-02,
        -5.61118592e-03, -6.30997345e-02, -4.86089522e-03,  1.09381496e-03,
         3.98655422e-02, -2.33366676e-02,  2.66447924e-02,  1.15885576e-02,
         3.64392512e-02, -1.01747317e-02, -8.40339810e-03, -3.75115052e-02,
        -6.16945268e-04, -4.39690724e-02, -1.60296261e-02,  4.37864736e-02,
         4.56061698e-02,  2.08404921e-02,  8.35703239e-02, -8.42563808e-02,
         2.17195172e-02,  5.64461872e-02, -1.02709820e-02, -3.10201179e-02,
         5.87496050e-02, -2.51185838e-02, -4.06530574e-02,  1.22026298e-02,
        -3.45984101e-02, -4.82924581e-02,  1.30593618e-02, -1.21560898e-02,
         4.32368331e-02,  1.64662935e-02,  4.47573885e-02,  2.90455930e-02,
        -4.52054963e-02, -5.68112507e-02,  3.30339116e-03,  9.09403712e-02,
        -1.58252195e-02,  1.75256990e-02,  4.22259644e-02,  2.09214874e-02,
        -2.69692764e-02,  1.68937203e-02, -3.34032178e-02,  7.10103437e-02,
         4.51791137e-02, -1.28518194e-01, -8.57827428e-04,  8.23351070e-02,
        -1.92921925e-02, -7.67287016e-02, -2.34796498e-02,  5.15716523e-02,
        -3.99690494e-02, -3.96374241e-02, -1.64537132e-02,  9.70269144e-02,
        -8.32322240e-02, -1.06569551e-01,  2.78160367e-02,  2.08292753e-02,
         6.46926761e-02, -2.44819503e-02, -7.92279840e-02, -1.70035919e-32,
        -8.47389400e-02,  3.36991413e-03, -4.96139005e-02, -7.46288970e-02,
         1.32793225e-02, -1.80579070e-02,  6.82973536e-03, -1.10734608e-02,
        -2.81403773e-02, -4.53512073e-02, -2.99682487e-02,  1.22094350e-02,
         3.91569473e-02,  1.06385253e-01,  3.29999141e-02, -1.18821934e-01,
         4.52494472e-02,  1.08704217e-01,  2.64669005e-02, -3.48592252e-02,
         4.44955342e-02,  1.82080008e-02, -7.13655609e-04, -6.98008165e-02,
         9.96401161e-02,  1.33902784e-02,  1.04348429e-01, -4.53811847e-02,
        -5.01634181e-02,  3.91014777e-02, -1.69257578e-02, -2.20518820e-02,
        -4.17718627e-02,  4.83728722e-02, -2.87748743e-02, -3.21229585e-02,
        -1.66043267e-02, -2.19527520e-02,  1.46573503e-02, -3.82604785e-02,
        -6.05040640e-02,  5.69180809e-02,  2.93610748e-02, -1.20060712e-01,
        -5.22321351e-02, -6.65216669e-02, -3.43150124e-02,  2.24657413e-02,
        -1.25614051e-02, -6.02216348e-02,  5.46143949e-02, -4.88448367e-02,
        -3.28398943e-02, -9.12784599e-03,  9.32900831e-02,  2.79505178e-02,
         4.08750847e-02,  5.99292964e-02,  6.17009401e-02,  1.61272451e-01,
        -5.83146028e-02, -8.40037614e-02, -8.68289918e-02,  5.20216785e-02,
         4.08934429e-02,  2.98099108e-02,  1.82428733e-02,  1.37743242e-02,
         6.47609457e-02,  2.19360869e-02, -3.46105359e-02,  1.89134721e-02,
         4.37506996e-02,  2.49588601e-02,  3.17166187e-02,  2.88717095e-02,
         6.45168275e-02, -4.22136895e-02, -6.45063743e-02,  3.78342010e-02,
        -3.26147936e-02,  1.16436578e-01, -5.82268126e-02, -1.31505225e-02,
        -1.78511720e-02,  9.86968633e-03, -4.50902589e-04, -8.82414952e-02,
        -1.33502498e-01,  5.19611426e-02, -6.11521453e-02,  5.27508184e-03,
        -1.81405284e-02,  3.14381756e-02, -5.75904474e-02,  9.29835721e-33,
        -3.34457941e-02,  9.49194357e-02, -1.19547352e-01,  2.64467318e-02,
         3.75640839e-02, -4.91904421e-03,  1.19949030e-02, -2.17732079e-02,
        -8.46098363e-02,  5.50461598e-02,  1.01681622e-02, -4.27040905e-02,
         3.30819897e-02,  1.35009782e-02, -1.68469734e-02, -3.30918729e-02,
         6.96457829e-03, -6.70922026e-02,  1.29356864e-03,  1.28886867e-02,
         1.06543042e-02,  7.86014870e-02, -6.87824637e-02, -1.24179544e-02,
        -1.21671855e-02, -2.04219837e-02, -8.82314444e-02,  4.93101440e-02,
        -6.62501976e-02, -2.16862857e-02, -8.76820758e-02, -9.38248113e-02,
        -4.84015234e-03,  4.02982049e-02,  5.10269664e-02, -9.78148542e-03,
         8.17413181e-02,  6.59386441e-03,  1.78066883e-02,  4.86117899e-02,
         5.53758293e-02, -1.46036660e-02, -4.41236310e-02, -1.98720749e-02,
        -5.75495027e-02, -3.81330587e-02, -6.84073716e-02,  1.73331406e-02,
        -5.67756854e-02, -1.81357227e-02, -4.77159582e-03, -2.10513826e-02,
        -7.71226957e-02, -2.11191829e-03, -4.08133790e-02,  1.44615890e-02,
         7.37873539e-02,  3.95747386e-02, -3.47848535e-02,  1.15301851e-02,

In [33]:
def find_best_match_index(query_embedding, embeddings):
    scores = [np.dot(query_embedding, emb) for emb in embeddings]
    best_idx = np.argmax(scores)
    return best_idx, scores[best_idx]

In [34]:
data[0]

{'paragraphe': 'DeepSeek-V3 Technical Report DeepSeek-AI research@deepseek.com Abstract We present DeepSeek-V3, a strong Mixture-of-Experts (MoE) language model with 671B total parameters with 37B activated for each token.To achieve efficient inference and cost-effective training, DeepSeek-V3 adopts Multi-head Latent Attention (MLA) and DeepSeekMoE architec- tures, which were thoroughly validated in DeepSeek-V2.Furthermore, DeepSeek-V3 pioneers an auxiliary-loss-free strategy for load balancing and sets a multi-token prediction training objective for stronger performance.We pre-train DeepSeek-V3 on 14.8 trillion diverse and high-quality tokens, followed by Supervised Fine-Tuning and Reinforcement Learning stages to fully harness its capabilities.Comprehensive evaluations reveal that DeepSeek-V3 outperforms other open-source models and achieves performance comparable to leading closed-source models.Despite its excellent performance, DeepSeek-V3 requires only 2.788M H800 GPU hours for its full training.In addition, its training process is remarkably stable.Throughout the entire training process, we did not experience any irrecoverable loss spikes or perform any rollbacks.The model checkpoints are available at https://github.com/deepseek-ai/DeepSeek-V3.MMLU-Pro (EM) GPQA-Diamond (Pass@1) MATH 500 (EM) AIME 2024 (Pass@1) Codeforces (Percentile) SWE-bench Verified (Resolved) 0 20 40 60 80 100 Accuracy / Percentile (%) 75.9 59.1 90.2 39.2 51.6 42.0 66.2 41.3 74.7 16.7 35.6 22.6 71.6 49.0 80.0 23.3 24.8 23.8 73.3 51.1 73.8 23.3 25.3 24.5 72.6 49.9 74.6 9.3 23.6 38.8 78.0 65.0 78.3 16.0 20.3 50.8 DeepSeek-V3 DeepSeek-V2.5 Qwen2.5-72B-Inst Llama-3.1-405B-Inst GPT-4o-0513 Claude-3.5-Sonnet-1022 Figure 1 | Benchmark performance of DeepSeek-V3 and its counterparts.',
 'word_count': 222,
 'char_count': 1767,
 'tokens_count': 441,
 'sentence_count': 10,
 'page_number': 1,
 'embedding': array([-7.36545101e-02, -5.92405535e-02,  5.75507917e-02,  7.15857446e-02,
         1.54401911e-02, -1.63372289e-02, -7.57387280e-02, -7.95286731e-04,
        -2.40841825e-02, -6.18494526e-02, -1.24292113e-01, -1.00587502e-01,
        -2.54351702e-02, -4.82992306e-02,  1.18151614e-02,  2.85590384e-02,
         5.89606017e-02,  6.40023202e-02, -1.25724912e-01, -8.45907107e-02,
         2.48465836e-02,  1.34899113e-02,  5.55628873e-02, -2.93894038e-02,
         2.66428962e-02,  5.07843122e-02, -1.18925818e-03, -1.09014049e-01,
         1.42405117e-02, -6.30987585e-02,  4.47497256e-02, -3.49189080e-02,
         3.93743142e-02,  1.80438850e-02, -4.82038371e-02,  1.15270421e-01,
        -1.40792429e-01, -8.29446614e-02,  3.17647830e-02, -6.87950104e-02,
         2.28424696e-03,  1.05707943e-02, -1.77034661e-02,  6.14538342e-02,
         5.65049760e-02,  5.83483316e-02,  3.36036533e-02, -7.81908631e-02,
         4.88184020e-02, -2.30751317e-02, -6.04354627e-02, -8.41500908e-02,
         4.49782461e-02,  5.46326153e-02, -5.16212285e-02,  7.21360906e-04,
         4.17707264e-02,  2.89894994e-02,  5.72450459e-03,  3.40614133e-02,
        -1.68882925e-02, -9.43698063e-02,  4.41695144e-03, -5.72452508e-02,
         6.95676869e-03, -4.72279489e-02,  5.50259138e-03,  4.24455032e-02,
        -2.06548180e-02,  4.80773626e-03,  4.01677238e-03,  1.35990873e-01,
        -1.70332361e-02, -5.26663195e-03, -5.73401386e-03,  9.73371193e-02,
         7.63155073e-02,  2.71089356e-02,  1.15384966e-01, -8.60132724e-02,
         6.24588877e-03, -1.76614746e-02,  1.49291661e-02, -3.23114321e-02,
         1.20315783e-01, -1.37790041e-02, -8.84563848e-03,  2.89110243e-02,
        -3.97716239e-02,  3.87413390e-02, -4.51677851e-02, -1.99127197e-02,
         7.55467117e-02, -1.02538932e-02,  5.05393073e-02,  7.40994066e-02,
        -5.52553013e-02, -8.12891349e-02, -1.27333492e-01,  9.85729247e-02,
        -3.42265610e-03,  7.89162144e-02,  7.80439898e-02,  1.86082721e-02,
         1.12325568e-02, -1.78675018e-02,  4.59726714e-02, -6.15691068e-04,
         2.82680131e-02,  4.67756623e-03,  6.36407286e-02,  5.93631975e-02,
         9.21989679e-02, -1.61985736e-02, -1.96268968e-02,  6.67901859e-02,
        -5.10301068e-02, -4.22006696e-02, -8.15443788e-03,  8.30097869e-02,
        -4.52640317e-02, -2.43692156e-02, -7.55408779e-03, -4.52205203e-02,
        -2.43633147e-03, -1.28824878e-02, -2.17346475e-02,  4.66412502e-33,
        -1.92291476e-02,  3.38960253e-02,  3.02155968e-02, -4.38047163e-02,
         8.15873872e-03, -4.60115448e-02, -5.31847868e-03,  3.41555364e-02,
        -6.64872304e-02, -2.31052544e-02, -2.03916319e-02, -1.87412165e-02,
        -6.49015456e-02,  1.46500811e-01, -1.07832355e-02, -2.74298862e-02,
        -3.59992459e-02,  6.53540045e-02, -2.21363008e-02, -8.84282228e-04,
         7.90865645e-02, -3.85905169e-02, -6.55979514e-02, -6.07736148e-02,
         3.70096904e-03, -7.66620785e-03,  9.32073668e-02, -6.14669584e-02,
        -6.73091412e-03,  1.01368269e-02, -1.30949438e-01, -3.43734138e-02,
        -2.12248862e-02,  4.29290570e-02,  1.55341523e-02, -5.71324788e-02,
        -2.98370514e-02, -4.55813110e-02, -6.02533156e-03, -1.21637676e-02,
         4.42576921e-03,  6.30749539e-02,  1.62854400e-02, -2.60945149e-02,
        -8.20358545e-02, -5.87974340e-02,  3.03448900e-03, -2.76656114e-02,
        -2.90018488e-02,  8.78179818e-03,  1.61610339e-02, -3.56828533e-02,
        -2.37761140e-02, -5.01886159e-02,  3.18017937e-02, -3.44655998e-02,
         5.44531457e-02,  9.16673690e-02,  4.57444452e-02,  3.14397998e-02,
         7.44727300e-03,  2.81543545e-02,  1.57230385e-02,  1.13029666e-01,
         8.45999271e-03,  6.37475997e-02, -9.57024191e-03,  1.46056026e-01,
         1.61169805e-02,  2.47888509e-02, -8.02993192e-04,  1.64082423e-02,
         3.95082682e-02, -2.65461765e-02, -6.04664534e-03,  1.16666434e-02,
         4.71574217e-02, -1.01466395e-01,  1.52230971e-02,  3.13782766e-02,
         1.87016241e-02,  6.05213456e-02, -2.29711905e-02,  2.80696489e-02,
        -1.19734174e-02, -3.50229442e-02,  6.42543240e-03, -8.83941129e-02,
         1.88682806e-02,  1.53512871e-02, -2.00651754e-02, -4.57690842e-02,
        -3.07951421e-02, -2.99285073e-03, -7.25532025e-02, -2.80538357e-33,
        -1.79780211e-04,  6.79054111e-02, -4.98998240e-02,  6.09748289e-02,
        -3.32329907e-02, -1.72712114e-02, -4.13232371e-02,  5.03200851e-02,
        -6.12706877e-02,  1.30293407e-02,  8.57344549e-03, -2.62614582e-02,
         6.47765696e-02, -2.39429623e-02,  6.25177696e-02, -1.66653823e-02,
        -2.22485755e-02,  8.12776946e-03,  1.64038669e-02, -1.03466781e-02,
         3.06867752e-02,  6.58851862e-02, -7.84938112e-02,  6.46218434e-02,
        -4.69758287e-02, -1.86146647e-02, -5.43937124e-02,  7.00666234e-02,
        -5.85723156e-03, -1.42591465e-02, -5.12143224e-03, -1.62344724e-02,
        -2.01102719e-02,  3.34333181e-02, -1.92594379e-02,  3.36539447e-02,
         6.61960840e-02, -1.80941802e-02, -1.77126154e-02,  3.14082541e-02,
         1.13496073e-01, -5.68226166e-02, -1.65281724e-02,  2.57995147e-02,
        -1.08513087e-01,  1.69489831e-02, -5.26489802e-02, -4.25187461e-02,
        -4.67190892e-03,  1.56408977e-02, -2.20717844e-02, -7.89547060e-03,
        -8.79504532e-02, -1.41685363e-03, -7.41648823e-02, -6.89151809e-02,
         1.32032193e-03,  7.18301255e-03,  4.22402620e-02, -1.29507231e-02,
        -5.94598837e-02, -2.15145014e-02,  4.72501665e-02, -4.47048061e-02,
         1.82686392e-02, -3.41442823e-02, -2.28104554e-02,  3.97904292e-02,
         2.98106037e-02, -1.37344999e-02,  1.47425421e-02, -8.66571907e-03,
         6.74800202e-02,  9.42610428e-02, -6.54761493e-03,  6.23168200e-02,
         5.53143881e-02, -7.30767474e-02, -1.26313902e-02, -3.48972790e-02,
         3.29144532e-03,  1.93192456e-02, -5.01440652e-03,  4.39123586e-02,
         6.30708486e-02,  7.76557177e-02,  1.89033523e-02,  6.32455647e-02,
        -2.61266194e-02,  4.19540294e-02, -6.05345368e-02,  5.59334643e-02,
        -4.70450148e-02,  1.07230477e-01, -4.37842235e-02, -4.39244445e-08,
        -4.54436913e-02,  5.85300773e-02,  3.94488201e-02,  3.78575847e-02,
         1.00979973e-02, -7.13360235e-02, -2.50397958e-02,  9.42401737e-02,
        -4.34387801e-03,  4.68532145e-02,  9.48943570e-02, -1.58426464e-02,
        -5.22853881e-02, -6.73166960e-02,  2.37377398e-02,  6.27047047e-02,
         2.45904569e-02,  1.48554081e-02, -7.40337605e-03, -5.34284934e-02,
         6.22454993e-02,  4.06175442e-02,  7.12228939e-02, -7.54844695e-02,
         5.87192699e-02, -7.54838064e-02, -2.89883893e-02,  8.29493552e-02,
        -1.11948792e-02, -3.05846762e-02,  6.50292204e-04,  2.79335342e-02,
        -2.71967314e-02, -9.44096223e-02,  2.87864897e-02,  1.28622815e-01,
        -2.21352912e-02, -2.42820401e-02,  5.68571128e-02, -2.05320166e-03,
         2.89760754e-02,  1.02703810e-01, -2.61279773e-02,  1.42625710e-02,
        -1.83888730e-02, -6.10387279e-03, -5.25135919e-02, -4.78076078e-02,
         5.91903254e-02, -3.91051918e-02, -7.87664857e-03,  5.99237997e-03,
         1.03719635e-02,  9.41201523e-02,  2.99628228e-02,  5.04732653e-02,
        -3.61868516e-02, -1.43785554e-03,  3.96512710e-02,  5.43301404e-02,
         6.14602715e-02, -7.25980103e-02, -4.58648019e-02,  2.27012802e-02])}

1.design query

In [36]:
import torch
import numpy as np
from sentence_transformers import util,SentenceTransformer
from time import perf_counter as timer
query = "Inputs of the Linear after the attention operator."
embeddings_tensor = torch.tensor(np.array(embeddings), dtype=torch.float32)
#embeding the query 
query_embedding = model.encode(query,device=device)
dot_product = util.dot_score(a=query_embedding, b=embeddings_tensor)[0]

best_idx = torch.argmax(dot_product).item()
best_text = pages_and_texts[best_idx]["text_of_page"]
best_page = pages_and_texts[best_idx]["page_number"]

print(f"Page: {best_page}")
print(f"Text: {best_text}")

Page: 18
Text: values across prior iterations to infer the current value. In order to ensure accurate scales and simplify the framework, we calculate the maximum absolute value online for each 1x128 acti- vation tile or 128x128 weight block. Based on it, we derive the scaling factor and then quantize the activation or weight online into the FP8 format. 3.3.3. Low-Precision Storage and Communication In conjunction with our FP8 training framework, we further reduce the memory consumption and communication overhead by compressing cached activations and optimizer states into lower-precision formats. Low-Precision Optimizer States. We adopt the BF16 data format instead of FP32 to track the first and second moments in the AdamW (Loshchilov and Hutter, 2017) optimizer, without incurring observable performance degradation. However, the master weights (stored by the optimizer) and gradients (used for batch size accumulation) are still retained in FP32 to ensure numerical stability throughout training. Low-Precision Activation. As illustrated in Figure 6, the Wgrad operation is performed in FP8. To reduce the memory consumption, it is a natural choice to cache activations in FP8 format for the backward pass of the Linear operator. However, special considerations are taken on several operators for low-cost high-precision training: (1) Inputs of the Linear after the attention operator. These activations are also used in the backward pass of the attention operator, which makes it sensitive to precision. We adopt a customized E5M6 data format exclusively for these activations. Additionally, these activations will be converted from an 1x128 quantization tile to an 128x1 tile in the backward pass. To avoid introducing extra quantization error, all the scaling factors are round scaled, i.e., integral power of 2. (2) Inputs of the SwiGLU operator in MoE. To further reduce the memory cost, we cache the inputs of the SwiGLU operator and recompute its output in the backward pass. These activations are also stored in FP8 with our fine-grained quantization method, striking a balance between memory efficiency and computational accuracy. Low-Precision Communication. Communication bandwidth is a critical bottleneck in the training of MoE models. To alleviate this challenge, we quantize the activation before MoE up-projections into FP8 and then apply dispatch components, which is compatible with FP8 Fprop in MoE up-projections. Like the inputs of the Linear after the attention operator, scaling factors for this activation are integral power of 2. A similar strategy is applied to the activation gradient before MoE down-projections. For both the forward and backward combine components, we retain them in BF16 to preserve training precision in critical parts of the training pipeline. 3.4. Inference and Deployment We deploy DeepSeek-V3 on the H800 cluster, where GPUs within each node are interconnected using NVLink, and all GPUs across the cluster are fully interconnected via IB. To simultaneously ensure both the Service-Level Objective (SLO) for online services and high throughput, we employ the following deployment strategy that separates the prefilling and decoding stages. 18